### ISSUE TITLE
use hiopVector instead of double, otherwise GCC throws a compilation error

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#100]
Should use `hiopVector& x = *iter.get_x();`
https://github.com/LLNL/hiop/blob/be0067082fcb540ffb9cdaf68ae5ea857ac3e383/src/Optimization/hiopAlgFilterIPM.cpp#L449
Otherwise GCC complains at line 451 when calling `nlp->eval_f`.

Similarly, 
https://github.com/LLNL/hiop/blob/be0067082fcb540ffb9cdaf68ae5ea857ac3e383/src/Optimization/hiopAlgFilterIPM.cpp#L491

**Comment by cnpetra** [comment]
fixed by 2d943c2
