### ISSUE TITLE
sparse-develop branch lacking implementations of RAJA functions

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#109]
Branch `ci-cmake-fix#107` contains only fixes to CMake changes integrated into branch `develop`. Building branch `ci-cmake-fix#107` on newell produces:

```
/people/manc568/projects/hiop/src/LinAlg/hiopLinAlgFactory.cpp: In static member function ‘static hiop::hiopMatrixSparse* hiop::LinearAlgebraFactory::createMatr
ixSparse(int, int, int)’:
/people/manc568/projects/hiop/src/LinAlg/hiopLinAlgFactory.cpp:173:71: error: invalid new-expression of abstract class type ‘hiop::hiopMatrixRajaSparseTriplet’
     return new hiopMatrixRajaSparseTriplet(rows, cols, nnz, mem_space_);
                                                                       ^
```

Which appears to be an error independent from library discovery code. I believe this is because functions have been added to sparse matrix interface (such as `copyDiagMatrixToSubblock`) without RAJA implementations, therefor breaking all RAJA/Umpire code. 

This issue branches off of issue #107.

CC @pelesh @cnpetra @nychiang

**Comment by cnpetra** [comment]
I think this was closed by PR #120, @nychiang  or @ashermancinelli please confirm/infirm.

**Comment by nychiang** [comment]
No. I think some functions are still missing, e.g., transfer Yale format to CSR format.

**Comment by cnpetra** [comment]
> No. I think some functions are still missing, e.g., transfer Yale format to CSR format.

`hiopMatrixRajaSparseTriplet:: convertToCSR` needed only for sparse linear solver with device interface (which we will not have in the near future). I suggest we close if there aren't other methods missing @nychiang
