### ISSUE TITLE
Repo mirror switch ssh to https

### ISSUE THREAD

**Issue by GitBytes** [LLNL/hiop#119]
Because of firewall and policy constraints on port 22, gitlab.pnnl.gov is using 2222 for ssh git commands. The current Actions Market place tool used to sync is forcing to port 22.

Plan:
Fork the current market place addon and change the port to 2222 and try again.

I'll take this on, just making note.

poke @ashermancinelli @pelesh

**Comment by GitBytes** [comment]
Current workflow run with error:
https://github.com/GitBytes/hiop/actions/runs/373423768

**Comment by GitBytes** [comment]
I am working on this now. Sorry for any delay in fixing this.

**Comment by GitBytes** [comment]
@ashermancinelli @pelesh @cnpetra,
I am not sure we got the right values into the secrets as described. How can I help confirm keys and values? If you want to post a picture from settings as I did in https://github.com/LLNL/hiop/pull/122#issuecomment-732536355 I can see the KEYS defined. If you need clarification on values I can send out an email but to start there are described values for this use case in that ticket. Cheers!

**Comment by cnpetra** [comment]
I updated them and received confirmation from @ashermancinelli that it works.

**Comment by ashermancinelli** [comment]
Merged in #126
