### ISSUE TITLE
HiOp Performance Profiling

### ISSUE THREAD

**Issue by CameronRutherford** [LLNL/hiop#127]
In order to track the performance of HiOp over time, example scripts should be added that will generate application profiles that highlight areas of inefficiencies and/or potential performance gain. Along with these, there should be sufficient documentation for results to be re-produced and re-interpreted.

To resolve this issue:

- [ ] Add a directory where example performance analysis scripts are provided
- [ ] Document usage, along with any specific notes on profiling
- [ ] Provide baseline performance metrics to compare future results against

For NVIDIA GPUs, I recommend using Nsight Systems for an application timeline, and Nsight Compute for kernel-based profiles once the key kernels have been identified. NVTX could also be used to annotate HiOp to highlight key application sections.

For AMD and other non-NVIDIA GPUs, TAU and HPCToolkit seem like reasonable options to provide basic performance profiling if need be.

CC: @vamatya @pelesh

**Comment by ashermancinelli** [comment]
For future reference I recommend keeping only the problem in the description and discussing possible solutions in the thread.

**Comment by ashermancinelli** [comment]
@CameronRutherford If I understand correctly, we have already documented our process for profiling on PNNL clusters and we have a system in place to coordinate with ORNL on profiling moving forward. If this is the case, can you document these two bullets:

- Document usage, along with any specific notes on profiling
- Provide baseline performance metrics to compare future results against

in a comment on this issue and close? I don't think we need the scripts in the repo if they're identical to other scripts and can be easily documented instead.

**Comment by CameronRutherford** [comment]
- Document usage, along with any specific notes on profiling

For profiling, we have been using the executable `nlpMDS_ex4_raja.exe` located in `<build_dir>/src/Drivers`. Before compiling this example, you should change HiOp's verbosity level to 0:

```diff
-  nlp.options->SetIntegerValue("verbosity_level", 3);
+  nlp.options->SetIntegerValue("verbosity_level", 0);
```
We are using Nsight Systems for the initial application timeline, along with command-line statistical analysis. To generate the application profile, you can use something along the lines of the following:

```shell
nsys_options=""
nsys_options="$nsys_options --output=$profile_output"
nsys_options="$nsys_options --trace=cuda,nvtx,mpi"
nsys_options="$nsys_options --mpi-impl=openmpi"
nsys_options="$nsys_options --cuda-memory-usage=true"
nsys profile $nsys_options mpirun -n 1 ./nlpMDS_ex4_raja.exe 400 100 1 -selfcheck
``` 
Once the profile is generated (output will be in `${profile_output}.qdrep`), you can use the stats command line switch for Nsight Systems to generate a summary of application performance:
```shell
profile_options=""
profile_options="$profile_options --report apigpusum" # gpusum"
profile_options="$profile_options --output $stats_output"
profile_options="$profile_options --force-overwrite true"
nsys stats $profile_options ${profile_output}.qdrep
``` 
This will result in an output file `stats.report_apigpusum.csv`.

- Provide baseline performance metrics to compare future results against

Given the generated `.csv` report, we can then review performance metrics. Do note that an application timeline can also be viewed by opening `${profile_output}.qdrep` in the Nsight Systems GUI.

From this report, there are three categories of operations recorded - CUDA_API, MEMROY_OPER, CUDA_KERNEL.

From viewing the application timeline and viewing the `.csv` data, it is clear that memory bandwidth is the key limiting factor in application performance. Because of this, I will outline some performance metrics based on the percentage of application time that is spent on memory operations. This is not an ideal metric. but it is the easiest to generate for the moment.

So, summing the percentage of time of our application spend on memory operations*, we end up with roughly 63.9% of application time being spent on memory operations. This seems to be the best baseline performance metric that we can come up with for the moment, and this should be minimized moving forward in order to optimize application performance.

\* Found by summing % of application time spent on:

- All CUDA_API operations related to memory operations (cudaFree, cudaMemcpyAsync, cudaMallocManaged, cudaMemcpy, cudaMemcpy2DAsync, cudaMemset, cudaHostAlloc) = 33.6 + 11.6 + 10.7 + 4.0 + 0.3 + 0.3 + 0.1 = 60.6%
- All MEMORY_OPER operations = 2.2%
- Any CUDA_KERNEL operations related to memory operations (only cublasCopyParams) = 1.1% 

@ashermancinelli closing this issue unless there is anything else you would like me to add
