### ISSUE TITLE
Inconsistent Formatting

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#129]
Formatting differences have made code review and readability more difficult and our style guidelines are no longer enough I believe. Eg in #120 formatting differences masked meaningful changes. Also, code formatting varies across the codebase which hinders readability.

**Comment by cnpetra** [comment]
differences in formatting, meaning  inconsistent blank characters or inconsistent tabulation/indentation?

**Comment by ashermancinelli** [comment]
Inconsistent whitespace/indentation as well as bracket style and function definitions etc. I suggest we use clang-format for automating the formatting bit. 

I'm using this .clang-format file for example. If you write these lines to file `.clang-format` in your root directory
```
BasedOnStyle: Chromium
DerivePointerAlignment: false
PointerAlignment: Left
BreakBeforeBraces: Allman
```
and format all files in HiOp (by running `clang-format -i <filename>`), it still builds and passes tests with no additional warnings. I formatted the whole repo with
```bash
$ find . -name '*.cpp' -o -name '*.c' -o -name '*.hpp' -o -name '*.h' \
    | xargs clang-format -i
```

This clang-format spec seems to match our style guidelines pretty closely. Would you like to take a look yourself? I can also push the formatted develop branch so you can see what the codebase would look like if we mandated formatting.

**Comment by cnpetra** [comment]
There is nothing wrong with the formatting HiOp uses in most of the code and I see no reason to change it. I do not like writing code with allman, but I am fine if you or someone is using it as long as is consistent for the hpp-cpp file pair.

**Comment by pelesh** [comment]
> There is nothing wrong with the formatting HiOp uses in most of the code and I see no reason to change it. I do not like writing code with allman. I am fine if you or someone is using it as long as is consistent for the hpp-cpp file pair.

@cnpetra, I think @ashermancinelli was pointing out to inconsistencies in code formatting rather than to a specific style. I think Allman style was agreed upon earlier and set as a rule in [README_developers](https://github.com/LLNL/hiop/blob/master/README_developers.md#indentation-braces-and-declarations), that is why it appears in the clang -format configuration. Whatever you decide to follow is OK imho, for as long as we all stick to it. I suggest you update style guidelines to your preferred style and we start from there.

**Comment by cnpetra** [comment]
we agreed that Allman should be used for developments coming from PNNL. I am sticking to what I've been using but also do not want to enforce the style on anybody else. I am fine with different styles coexisting as long as is consistent for the hpp-cpp file pair.

**Comment by cnpetra** [comment]
discussion moved to PR#194
