### ISSUE TITLE
Compiling HiOp on Mac (v 10.14.6)

### ISSUE THREAD

**Issue by steffi7574** [LLNL/hiop#13]
I'm getting linker errors of the following type:
[ 68%] Linking CXX executable nlpDenseCons_ex3.exe
Undefined symbols for architecture x86_64:
  "_daxpy_", referenced from:
      hiop::hiopVectorPar::axpy(double, hiop::hiopVector const&) in libhiop.a(hiopVector.cpp.o)
      hiop::hiopMatrixDense::addMatrix(double, hiop::hiopMatrix const&) in libhiop.a(hiopMatrix.cpp.o)

Openblas, Lapack, OpenMPI are installed.

This is the cmake output:
[cmake_out.txt](https://github.com/LLNL/hiop/files/4168441/cmake_out.txt)

**Comment by steffi7574** [comment]
Seems like cmake is not picking up lapack. Solution:
In a clean build directory
> cmake -DLAPACK_LIBRARIES="-L/usr/lib -llapack -lblas" ..
where the location of those libraries (here /usr/lib/) can be found with
> locate liblapack
> locate libblas

**Comment by gollnlp** [comment]
thanks Stefanie
