### ISSUE TITLE
Unit Tests for Complex Classes

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#130]
We are currently not testing any complex linear algebra classes.

Tests for `hiopMatrixDense` should almost perfectly apply to `hiopMatrixComplexDense`, as with `hiopMatrixSparseTriplet` and `hiopMatrixComplexSparseTriplet` etc. The *MDS classes are pure encapsulations of the sparse and dense classes, so I presume we will be able to reuse many tests there as well.

@cnpetra What is the plan for complex classes moving forward?

**Comment by cnpetra** [comment]
Nothing in sight in the foreseeable future. Complex lin algebra supports a particular feature that is not at the core of any solvers. While having unit testing for these doesn't hurt, it should be at the very bottom of your priority list.

**Comment by ashermancinelli** [comment]
I think we should close this issue then. If we move forward with complex classes we can address their tests then. @pelesh thoughts?

**Comment by cnpetra** [comment]
> I think we should close this issue then. If we move forward with complex classes we can address their tests then. @pelesh thoughts?

agreed
