### ISSUE TITLE
No automated builds of many configuration options

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#132]
We currently automate a small subset of possible hiop builds, each with GCC 7 or similar release.

- PNNL CI uses BUILD.sh script with all options enabled
- ORNL CI uses BUILD.sh script with all options enabled
- Github actions build uses default cmake build with most options disabled

Because of how few of the possible configurations we test with, we've had numerous issues (eg #46, #47,  #121).

Following discussion, these are completion criteria:

- [x] weekly/nightly long build
- [x] cmake option for running valgrind on integration tests

**Comment by ashermancinelli** [comment]
Now that we have many CI platforms enabled, I propose we run a very long nightly/weekly job to build/test hiop with a large subset of the possible configurations. 

CC @pelesh

**Comment by cnpetra** [comment]
to add to this, maybe we can add something like `HIOP_WITH_VALGRIND_TESTS` to run valgrind on select driver executables?

**Comment by ashermancinelli** [comment]
> to add to this, maybe we can add something like `HIOP_WITH_VALGRIND_TESTS` to run valgrind on select driver executables?

Added to completion criteria.

**Comment by ashermancinelli** [comment]
I think this would be immensely simplified by using the hiop spack package which we'll probably have polished by end of Q1. We can revisit Q2 I think.

**Comment by ashermancinelli** [comment]
Tracked in branch `full-build-matrix-dev`.

**Comment by ashermancinelli** [comment]
Resolved by #146
