### ISSUE TITLE
METIS-related build error

### ISSUE THREAD

**Issue by cnpetra** [LLNL/hiop#136]
When `HIOP_SPARSE` is on but coinhsl cannot be found (and `HIOP_SPARSE` is disabled), cmake build system still adds metis library. Later, linking of executables fails as metis lib is not found. Quick fix is to `-DMETIS_DIR=...`, but I think the logic in cmake build system should be improved to not include metis when `HIOP_SPARSE` is disabled (and `HIOP_WITH_KRON_REDUCTION` is off)

**Comment by nychiang** [comment]
I will address this in PR #104

**Comment by cnpetra** [comment]
fixed by faa4527b882107e7b93c3b614197a3bfed94e446
