### ISSUE TITLE
CMake V3.15+ is required to link to STRUMPACK.

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#143]
When compiling HiOp and using FindHiopSTRUMPACK.cmake to find Strumpack, CMake needs to load the .cmake configuration files under STRUMPACK. This requires CMake with version 3.15+, but the project-specific compiler module for ExaSGD on Summit uses cmake/3.13.4.

An example of the error message is:
```
CMake Error at /g/g92/chiang7/software/STRUMPACK/install_db/lib/cmake/STRUMPACK/strumpack-config.cmake:4 (list):
  list does not recognize sub-command PREPEND
Call Stack (most recent call first):
  cmake/FindHiopSTRUMPACK.cmake:13 (find_package)
  CMakeLists.txt:206 (include)
```

**Comment by cnpetra** [comment]
I was able to build everything with `module load cmake/3.17.3`

How long ago was CMake 3.15 released? We may just require minimum 3.15 to keep things simple. 

@ashermancinelli

**Comment by nychiang** [comment]
CMake 3.15 was released on 17 July 2019

**Comment by ashermancinelli** [comment]
> We may just require minimum 3.15 to keep things simple.

I'm fine with that, I think we already have >=3.15 on all platforms.

**Comment by cnpetra** [comment]
ok, let's require 3.15 minimum since it is "old" enough to be readily available

**Comment by ashermancinelli** [comment]
I just made a branch to ensure HiOp works with cmake 3.15 on all of our platforms and it's working. Do you mind if I push directly to develop? @cnpetra

**Comment by ashermancinelli** [comment]
Pushed to develop.
