### ISSUE TITLE
Adapt HiOp model interface to support GPU execution using device memory

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#147]
Some HiOp's interface methods (e.g. `get_cons_info`) provide access to data that resides in CPU _and_ GPU memory. This makes it difficult to use device memory and so far HiOp GPU computations have been enabled only with unified virtual memory. Consider making each HiOp interface method access all of its data _either_ on CPU _or_ on GPU. That would simplify adding support for computations in the device memory (in addition to computations in UVM) when running GPU computations.

**Comment by pelesh** [comment]
Based on discussion with @cnpetra, I suggest following memory space for HiOp model interface methods:

### Abstract HiOp interface
| Method                   | Description                                                       | Suggested Execution Space |
| ------------------------ | ----------------------------------------------------------------- | ------------------------- |
| `get_prob_sizes`         | returns problem sizes                                             |  host | 
| `get_vars_info`          | provides variables upper/lower limits, nonlinearity type          |  device | 
| `get_cons_info`          | provides constraints upper/lower limits, nonlinearity type        |  device | 
| `eval_f`                 | evaluates objective function                                      |  device | 
| `eval_grad_f`            | evaluates gradient of the objective                               |  device | 
| `eval_cons` (overload 1) | evaluates either equality or inequality constraints               |  device | 
| `eval_cons` (overload 2) | evaluates both, equality and inequality constraints               |  device | 
| `get_MPI_comm`           | returns MPI communicator                                          |  host | 
| `get_vecdistrib_info`    | column partitioning specification for distributed memory vectors  |  host | 
| `get_starting_point`     | method providing a primal starting point                          |  host | 
| `solution_callback`      | callback for the optimal solution                                 |  device | 
| `iterate_callback`       | callback for the iteration                                        |  device | 

### HiOp dense interface
| Method                       | Description                                                   | Suggested Execution Space |
| ---------------------------- | ------------------------------------------------------------- | ------------------------- |
| `eval_Jac_cons` (overload 1) | Evaluates the Jacobian of equality _or_ inequality constraints  | device |
| `eval_Jac_cons` (overload 2) | Evaluates the Jacobian of equality _and_ inequality constraints | device |

### Hiop mixed dense-sparse interface
| Method                       | Description                                                   | Suggested Execution Space |
| ---------------------------- | ------------------------------------------------------------- | ------------------------- |
| `get_sparse_dense_blocks_info` | Returns sizes of sparse and dense Jacobian blocks             | host |
| `eval_Jac_cons` (overload 1) | Evaluates the Jacobian of equality _or_ inequality constraints  | device |
| `eval_Jac_cons` (overload 2) | Evaluates the Jacobian of equality _and_ inequality constraints | device |
| `eval_Hess_Lagr`             | Evaluates Hessian in 3 structural blocks                        | device |

CC @nychiang @manc568

**Comment by cnpetra** [comment]
we should have a chat about potential changes to these -- as required by the possibility that we may have access to GPU linear solver computations only through a CPU (linear solver) interface

**Comment by cnpetra** [comment]
closing this as the discussion moved offline and a solution has been found.
