### ISSUE TITLE
Embedded linear algebra kernels in hiopIterate class

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#151]
Embedded kernels in [`addLinearDampingTermToGrad_x`](https://github.com/LLNL/hiop/blob/develop/src/Optimization/hiopIterate.cpp#L432) and [`addLinearDampingTermToGrad_d`](https://github.com/LLNL/hiop/blob/develop/src/Optimization/hiopIterate.cpp#L486) methods force execution on host (CPU). It would be good to bring these two methods in line with others in `hiopIterate` class methods and use vector kernels from the linear algebra module through an abstract interface. That would make `hiopIterate` agnostic of the memory space or execution policy.

CC @cnpetra @nychiang

**Comment by cnpetra** [comment]
addressed by PR #167
