### ISSUE TITLE
Enable using device memory space when running HiOp on GPU

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#152]
Currently execution on GPU works only when using unified virtual memory. To enable using device memory space, issues #94, #103, #147, and #151 need to be resolved, and PR #76 needs to be merged. The remaining work may involve some refactoring in `hiopNlpFormulation` class.

This issue is to coordinate all activities needed to enable HiOp GPU execution while using device memory space.

CC @cnpetra @ashermancinelli @nychiang

**Comment by cnpetra** [comment]
closing this since it has been addressed. Issue #103 is still active, but wasn't required for the resolution of this issue.
