### ISSUE TITLE
HiOp GPU-enabled build fails

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#16]
My HiOp build from `dev/NewtonMDS` branch fails at compile stage with message:
```
make[2]: *** No rule to make target `/usr/lib64/libopenblas.so -lmagma -L/share/apps/cuda/9.2/lib64 -lculibos -lcublas -lcublasLt -lnvblas -lcusparse -lcudart -lcudadevrt', needed by `src/LinAlg/test_hiopLinAlgComplex.exe'.  Stop.
```
It seems that there is some mess-up with CMake paths. I used following configuration for build:
```
CC=mpicc CXX=mpicxx FC=mpif90 cmake              \
-DHIOP_USE_MPI=1                                 \
-DHIOP_USE_GPU=1                                 \
-DHIOP_MAGMA_DIR="/.../exasgd/newell/magma" \
-DCMAKE_INSTALL_PREFIX=$HIOP_DIR                 \
../hiop
```
I used cmake 3.13.4, gcc 7.4.0, openmpi 3.1.3, cuda 9.2, OpenBLAS 0.3.3, and LAPACK 3.4.2 for the build. Configure part works fine, but something goes wrong with complex linear algebra compilation.

Verbose output gives me this:
```
make -f src/LinAlg/CMakeFiles/test_hiopLinAlgComplex.exe.dir/build.make src/LinAlg/CMakeFiles/test_hiopLinAlgComplex.exe.dir/depend
make[2]: Entering directory `/.../exasgd/src/hiop/build_newell'
cd /.../exasgd/src/hiop/build_newell && /.../cmake/3.13.4/bin/cmake -E cmake_depends "Unix Makefiles" /.../exasgd/src/hiop/hiop /.../exasgd/src/hiop/hiop/src/LinAlg /.../exasgd/src/hiop/build_newell /.../exasgd/src/hiop/build_newell/src/LinAlg /.../exasgd/src/hiop/build_newell/src/LinAlg/CMakeFiles/test_hiopLinAlgComplex.exe.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/.../exasgd/src/hiop/build_newell'
make -f src/LinAlg/CMakeFiles/test_hiopLinAlgComplex.exe.dir/build.make src/LinAlg/CMakeFiles/test_hiopLinAlgComplex.exe.dir/build
make[2]: Entering directory `/.../exasgd/src/hiop/build_newell'
make[2]: *** No rule to make target `/usr/lib64/libopenblas.so -L/.../exasgd/newell/magma/lib -lmagma -L/.../cuda/9.2/lib64 -lculibos -lcublas -lcublasLt -lnvblas -lcusparse -lcudart -lcudadevrt', needed by `src/LinAlg/test_hiopLinAlgComplex.exe'.  Stop.
```

**Comment by cnpetra** [comment]
Do you really want to use 3 dots in
-DHIOP_MAGMA_DIR="/.../exasgd/newell/magma" ?

In any case 'test_hiopLinAlgComplex.exe' should not be built in this branch. I've updated the branch to not build it.

pull dev/NewtonMDS and use the correct (absolute recommended) path to magma

**Comment by pelesh** [comment]
Is `nlpDenseCons_ex1.exe` example supposed to be built with `dev/NewtonMDS` branch? My HiOp build trips on that one, as well.

**Comment by pelesh** [comment]
A few more updates: 
- HiOp the library builds fine.  The build fails when building drivers. Each driver build fails with the same error message from the initial report.
- Everything builds fine when I disable GPU. It seems some make files are not configured correctly by CMake.

I will investigate more.

By the way, with what CMake version is HiOp tested? I tried 3.13 and 3.16.

**Comment by pelesh** [comment]
I was able to build examples manually. It seems that something in CMake code is broken. I'll troubleshoot more ...

Also, HiOp depends on `cuBLASLt` library, which is available only as of v10.1. I thought this was my problem, because I was building with CUDA 9.2, but apparently there is something else.

**Comment by cnpetra** [comment]
It's the other way around for me. With quotes works (and no quotes appear in the link command) and without it does not. Maybe is related to the underlying shell?

**Comment by pelesh** [comment]
> It's the other way around for me. With quotes works (and no quotes appear in the link command) and without it does not. Maybe is related to the underlying shell?

It may be due to different CMake versions. Removing quotes works for me for CMake >= 3.13 on Linux, bash. What configuration you use where the quotes are needed?

**Comment by pelesh** [comment]
By the way, below is the information on my bash version:
```console
$ bash --version
GNU bash, version 4.2.46(2)-release (powerpc64le-redhat-linux-gnu)
```

**Comment by cnpetra** [comment]
tested the PR and your update works well both on mac and ubuntu. closing this since the PR was merged
