### ISSUE TITLE
unused cmake variable in CI

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#165]
Some options are not available anymore and hence we can remove them from the cmake command.
For example, `HIOP_USE_UMPIRE` can be removed from [github test.yml](https://github.com/LLNL/hiop/blob/5cb86d291c962ed64c7b428616c1af5f8eeeb8af/.github/workflows/test.yml#L22)

In addition, `ENABLE_TESTING` should be replaced by `HIOP_WITH_MAKETEST` and/or `HIOP_WITH_VALGRIND_TESTS` on the mirror sites.

An example of cmake warning from the mirror site: 
Manually-specified variables were not used by the project:
    ENABLE_TESTING
    HIOP_USE_UMPIRE

**Comment by cnpetra** [comment]
closed by PR #222
