### ISSUE TITLE
HiOp not converging on some platforms

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#176]
In this log for example [marianas_exago.log](https://github.com/LLNL/hiop/files/5822794/marianas_exago.log), hiop fails to converge and produces many of warnings about 'Unusually large bound dual variables'. This case does converge on our Newell platform however.

CC @pelesh @abhyshr @cnpetra

**Comment by ashermancinelli** [comment]
@abhyshr can you provide additional context about how ExaGO uses HiOp for this case? hiop is the model and solver here.

**Comment by cnpetra** [comment]
the problem seems to be rank deficient. is it possible to provide equivalent log file for newel ?

**Comment by ashermancinelli** [comment]
[newell_hiop+pbhiop+activsg200.log](https://github.com/LLNL/hiop/files/5824707/newell_hiop%2Bpbhiop%2Bactivsg200.log)

**Comment by ashermancinelli** [comment]
I rebuilt every dependency and we're still seeing the same problem. Here's what I find now: [marianas.log](https://github.com/LLNL/hiop/files/5843594/marianas.log), [newell.log](https://github.com/LLNL/hiop/files/5843595/newell.log)

**Comment by ashermancinelli** [comment]
Note this is on magma 2.5.4

**Comment by cnpetra** [comment]
are you using `magma-inertia-dev` ?

**Comment by ashermancinelli** [comment]
I rebuilt everything with hiop and exago in debug mode from latest develop commit, and it has not solved the problem. Here are logs similar to last time: [marianas.log](https://github.com/LLNL/hiop/files/5850230/marianas.log), [newell.log](https://github.com/LLNL/hiop/files/5850231/newell.log)

**Comment by cnpetra** [comment]
closing this since we moved the discussion on pnnl gitlab
