### ISSUE TITLE
copyFromStarting method in RAJA vector fails if source vector is of zero length 

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#187]
Method `copyFromStarting` in RAJA vector will fail if the source vector is of zero length. Umpire copy method will check the data array size and throw exception if it is zero. This is different than behavior of `memcpy` in standard library, which is unaware of vector sizes. There has to be a check of source vector size in `copyFromStarting` and if it is zero, the function should return immediately.

CC @cnpetra @ashermancinelli @nychiang

**Comment by pelesh** [comment]
Unit test needs to be updated to catch bugs like this.

**Comment by CameronRutherford** [comment]
#192 Ensures that the size of the input vector is checked for the vector implementation of the `copyFromStarting` method in the RAJA Vector class.

Current vector unit tests ([here](https://github.com/LLNL/hiop/blob/develop/tests/LinAlg/vectorTests.hpp#L240)) already test copying from a zero size vector, and a zero size buffer.

Unless there is something additionally needed to close this issue, I think the remaining can be discussed in #189. 

The only thing that comes to mind is that the copyFromStarting method may not have ideal behaviour when called by a `this` vector that is empty. Currently, it will probably fall back on Umpire to throw an appropriate exception. See #188 for more discussion...

**Comment by cnpetra** [comment]
closed by PR #320
