### ISSUE TITLE
copyToStarting method in RAJA vector fails if destination vector is of zero length 

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#188]
If the destination vector is of zero length, there will be zero elements copied per `copyToStarting` implementation. However, unlike standard library `memcpy`, the Umpire copy method will check if array sizes are zero and if so, it will throw an exception before realizing that zero data will be copied to that location anyways.

The `copyToStarting` method should probably invoke the copy call only if it actually has any work to do.

CC @cnpetra @CameronRutherford @ashermancinelli

**Comment by CameronRutherford** [comment]
Firstly, there are two different implementations of the RAJA vector `copyToStarting` method. One checks to see if the place that is being copied into is empty, whereas the other checks to see if the place being copied from is empty. This should be consistent across both implementations, and I think this is a bug.

The testing for this can be covered in #189, but I think behaviour should be clarified first.

Considering #187, I think it would be better in both kernels to test both the src and destination vector for length 0 before invoking any Umpire memory operations. Perhaps some further discussion would be good on this, but this seems like an adequate solution.

**Comment by cnpetra** [comment]
closed by PR #320
