### ISSUE TITLE
Update unit tests for vector copy kernels to cover cases when source and/or destination are zero length vectors

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#189]
Umpire copy method throws exceptions whenever one of the input arguments points to a zero length data array. In some cases, HiOp wants to copy 0 elements to a 0 long array, for example. That should be legitimate action and easy to implement with Umpire or `memcpy`. We need to test those corner cases to make sure HiOp will behave as intended.

So far, a few of these cases slipped through existing tests. See e.g. #187 and #188.

CC @cnpetra @ashermancinelli

**Comment by cnpetra** [comment]
closed by PR #320
