### ISSUE TITLE
Coding style to distinguish class member variables

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#19]
It might be helpful to consider a coding style that makes class member variables distinguishable (e.g. ending each member variable name with `_`). IMHO it would significantly improve readability of the code, especially in functions that are a couple of hundreds lines long and operate on a few dozen variables. 

Considering the size of HiOp code, making a wholesale changes would require some work, but even setting style guidelines for future contributions would be quite helpful.

**Comment by cnpetra** [comment]
agree. I think I've changed the coding style at least one time as I worked on different project over the years :). do you have a coding style document/link?

**Comment by ashermancinelli** [comment]
It would be my preference to use [this](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md) style guideline. Would you two mind taking a look? We could add clang-tidy scripts to help us all write conformant code if that sounds good to you both.

**Comment by pelesh** [comment]
I agree with @ashermancinelli, the guidelines he referenced are becoming a gold standard pretty much. The relevant chapter for this discussion is I think in [Naming and Layout Rules](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-naming) chapter.

The only amend I would make is to use [Allman style](https://en.wikipedia.org/wiki/Indentation_style#Allman_style), rather than [K&R](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rl-knr), simply because it leads to a code that is easier to read in a large editor window.

In the end it is all very much a matter of personal taste. The most important thing is that we are all consistent. 

@cnpetra in the short term, it would be very helpful if you could set rules for distinguishing member from local variables.

**Comment by ashermancinelli** [comment]
I too prefer Allman style 😄 we could add some scripts for formatting errors when in HIOP_DEVELOPER_MODE to extend what Cosmin and I discussed in #22

**Comment by cnpetra** [comment]
cppcoreguildeline seems to be not very specific but it would be of value if we can enable code style warning/checking in DEVEL_MODE.

I am taking a shot below, please feel free to comment and suggest specific additional guidelines

indentation 
- my personal preference is for compact K&R (no separation of between "if" and "("), similar to C, but I am willing to switch to Allman (as long it can be enforced via clang-tidy or similar tool)
- two spaces alignment, maybe four if you like it better, but do not use tabs

naming 
- classes: Upper and lower case, no underscores
- data members: ending in `_`; lower case only and use `_` to separate 
- member methods:   lower case only and use `_` to separate 
 
 to be continued...

**Comment by cnpetra** [comment]
it wouldn't hurt and probably would be faster to look at M-FEM (https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#developer-guidelines). They have a make style

**Comment by pelesh** [comment]
@cnpetra what you suggest sounds reasonable. As I said, the most important thing is that we are consistent.

A couple of more references that might be helpful:
- The most detailed guidelines that I've seen are published by Stroustrup for [JSF program](http://www.stroustrup.com/JSF-AV-rules.pdf). These are a bit old and may not address recent C++ features. This seems to be a precursor to cppcoreguidelines.
- From ECP family, there are [NOX/Trilinos style guidelines](https://docs.trilinos.org/dev/packages/nox/doc/html/coding.html) that might be relevant for HiOp.

**Comment by ashermancinelli** [comment]
What naming convention for feature branches would be preferred? For example, always branch from master and name the branch `<feature or fix>-dev`

**Comment by cnpetra** [comment]
feature-developmentname or fix-bugname would do I guess. I use dev/devname and fix/fixname, but not for particular reason.

always branch from master, indeed, and master serves as `stable` for now.

**Comment by ashermancinelli** [comment]
I will change the PR accordingly. I prefer `-`s over `/`s so not to confuse ref pathnames and remotes with branch names.

**Comment by cnpetra** [comment]
closing this -- the discussion moved to the PR and we're in some kind of (initial) agreement
