### ISSUE TITLE
Invalid access to some undefined memory locations

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#193]
Valgrind reports some `Invalid read` errors at 3 lines in `matrixTestsSparse.hpp`. 
1. [Line 308](https://github.com/LLNL/hiop/blob/9eb026768bc5e0a2c1293d0487cc39913001ae19/tests/LinAlg/matrixTestsSparse.hpp#L308)
2. [Line 390](https://github.com/LLNL/hiop/blob/9eb026768bc5e0a2c1293d0487cc39913001ae19/tests/LinAlg/matrixTestsSparse.hpp#L390)
3. [Line 489](https://github.com/LLNL/hiop/blob/9eb026768bc5e0a2c1293d0487cc39913001ae19/tests/LinAlg/matrixTestsSparse.hpp#L489)

Suggested correct is to add `rs_di<nnz && rs_dj<nnz` into the while condition, e.g.,
`while(rs_di<nnz && rs_dj<nnz && iRow[rs_di] == d_i && iRow[rs_dj] == d_j)`

**Comment by pelesh** [comment]
Thanks for reporting @nychiang! @CameronRutherford and I have been looking into a number of minor issues in sparse matrix tests, and we'll take a look into this, as well. The cleanup of this code is past due.

**Comment by nychiang** [comment]
I have fixed these issues in PR#182 , since I need to implement some functions in the vector/matrix kernel.
