### ISSUE TITLE
Failed line search when more than one line search step is required

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#196]
Line search fails when more than step is required.
It will keep doing line search till terminate hiop with an error message, mentioning that step size is too small.

This problem can be reproduced in EX6, by setting parameter `mu0` to `0.1`.

**Comment by cnpetra** [comment]
as per our discussion, restoration phase is invoked. But it should not since the problems is convex and feasible. Any idea what  triggers the restoration phase/comes in contradiction with feasibility or convexity?

this may be related to the ex3 linearch failure at the last iteration(s)...

**Comment by nychiang** [comment]
Update: fixed in #216 and #239
