### ISSUE TITLE
unknown error in Ex3 with MPI

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#205]
When running EX3 with 5 variables on multiple MPI processes, some MPI function returns wrong values.
For example, in the latest `develop` branch ( 3/26/2021, commit [9eb6362](https://github.com/LLNL/hiop/commit/9eb6362a7d59cdd137cef396b52a83a9f0e50611) , negative values are returned when computing infinity norm ([here](https://github.com/LLNL/hiop/blob/9eb6362a7d59cdd137cef396b52a83a9f0e50611/src/Optimization/hiopResidual.cpp#L148))

In branch `ls-prob-fix`, HiOp is frozen at the 1st iteration.

NOTE that this problem only happens in EX3 with 5 variables. One cannot overserve this issue if there are more than 6 variables.

**Comment by nychiang** [comment]
Update:
this bug comes from removing fixed variables. In this 5 variables example, one MPI process has 0 variable after removing fixed variable. As a result, the distributed vector is not created correctly [here](https://github.com/LLNL/hiop/blob/627f4d890fb35bd6620fe50ea2f4b23b45d59715/src/Optimization/hiopNlpFormulation.cpp#L315), and MPI_ALL_REDUCE is not matched later.

@cnpetra seems this is not a quick fix. For all the MPI functions in the vector kernel, we need to test if its size is zero or not. If it is zero, add dummy MPI_Allreduce function to return an appropriate value.
I remember @pelesh mentioned a similar bug, i.e., vector with size zero, in another issue.

**Comment by cnpetra** [comment]
that makes a lot of sense

**Comment by nychiang** [comment]
@cnpetra 
I think PR #205 hasn't fixed this problem yet, and it still has mpi mismatches in the code.
When we solver Ex3 with 1 mpi or 2 mpi processes, we got different results. That is, the inf_pr computed with 2 mpi processes is wrong.
It seems this bug exists for a while, as it can be reproduced in v0.3 ([7e8adae](https://github.com/LLNL/hiop/commit/7e8adae).

**Comment by cnpetra** [comment]
will take a look

**Comment by cnpetra** [comment]
I cannot reproduce nor see anything wrong with ex3 on one and two ranks. Can you please email me the parameters/size of ex3 and the log file?

**Comment by cnpetra** [comment]
thanks, I reproduced and fixed the issue.
