### ISSUE TITLE
TPL CMake logic in top-level cmake lists

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#220]
Logic for third party libraries should not be in the top-level cmakelists.txt, but hidden in many other cmake files to break up the logic. [See SUNDIALS top-level cmake linked here](https://github.com/LLNL/sundials/blob/master/CMakeLists.txt#L167). Logic for each third party library ought to be modular and in seperate cmake files.

**Comment by cnpetra** [comment]
looks like this is also address, please confirm?
