### ISSUE TITLE
Unable to build with raja~openmp

### ISSUE THREAD

**Issue by CameronRutherford** [LLNL/hiop#229]
In nlpMDS_raja_ex4.cpp on lines [203](https://github.com/LLNL/hiop/blob/develop/src/Drivers/nlpMDS_raja_ex4.cpp#L203) and [242](https://github.com/LLNL/hiop/blob/develop/src/Drivers/nlpMDS_raja_ex4.cpp#L242), OpenMP execution policy is used explicitly. This causes a build error when attempting to build against a non OpenMP configured RAJA.

See PR [228](https://github.com/LLNL/hiop/pull/228) for an attempted solution to this.

This is an issue as currently RAJA has multiple OpenMP issues open, and so it is necessary to build RAJA without OpenMP at the moment. It might be worth configuring all RAJA execution policies based on whether OpenMP support is enabled as well.

cc @pelesh

**Comment by ashermancinelli** [comment]
[Linking this RAJA issue for reference.](https://github.com/LLNL/RAJA/issues/976)

**Comment by ashermancinelli** [comment]
> so "downgrading" RAJA execution policy to sequential seems to be a good temporary solution.

I agree

**Comment by cnpetra** [comment]
I think this has been addressed, but feel free to reopen if it wasn't
