### ISSUE TITLE
axdzpy_w_pattern is implemented, but not part of hiopVector abstract interface

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#23]
Method `axdzpy_w_pattern` is implemented in class `hiopVectorPar`, but there is no abstract interface to it in (almost) pure virtual class `hiopVector`. Is this method needed?

**Comment by cnpetra** [comment]
apparently it is used: https://github.com/LLNL/hiop/search?q=axdzpy_w_pattern&unscoped_q=axdzpy_w_pattern

I would add it  as pure vritual in the base class. I forgot to.
