### ISSUE TITLE
Make CUDA a first class language

### ISSUE THREAD

**Issue by CameronRutherford** [LLNL/hiop#230]
Related to closed MR [228](https://github.com/LLNL/hiop/pull/228).

Since we adopt CMake 3.18: in our spack package [here](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/hiop/package.py#L55), we are now able to treat CUDA as a first class language within HiOp, per [best practices](https://cliutils.gitlab.io/modern-cmake/chapters/packages/CUDA.html).

This is necessary to configure HiOp with spack from scratch, although our current find module works with our existing build system. When compiling with a spack CUDA without the changes in #228, there are issues linking against all the correct CUDA libraries (namely `-lcuda_runtime` supplied by Umpire and RAJA).

There may have to be some logic in determining if CUDA is available before making it a project language as in the MR, however #228 serves as an example of what these changes would entail.

cc @pelesh

**Comment by CameronRutherford** [comment]
@pelesh we included requiring CMake 3.18: in [HiOp's spack package](https://github.com/spack/spack/pull/22232) initially because of the use of specification of CUDA architectures in CMake. While we expressed this dependency there, it seems like this is something that would need to be changed in order to accommodate newer CMake and CUDA versions.

**Comment by pelesh** [comment]
> EDIT: specifically using `-DCMAKE_CUDA_ARCHITECTURES=` required this dependency

I see. So this is coming from the spack and as far as I can see, there is no such variable in HiOp's CMake code. Is it correct to say that you need CMake version >= 3.18 if you want to install HiOp with spack, but otherwise HiOp dependency is >= 3.12?

@cnpetra, if you are OK with bumping HiOp CMake requirement to >=3.18, that would help us make CUDA section of the CMake cleaner.

**Comment by CameronRutherford** [comment]
`Is it correct to say that you need CMake version >= 3.18 if you want to install HiOp with spack, but otherwise HiOp dependency is >= 3.12?`

@pelesh with how we have HiOp's spack package configured, that is a fair statement. This issue would probably have to be resolved before we can build with spack and cmake 3.18+.The other thing to note is that using `find_package(CUDA)` is deprecated with CMake 3.18
