### ISSUE TITLE
FR (sparse) problem contains host only code

### ISSUE THREAD

**Issue by cnpetra** [LLNL/hiop#232]
Externalize the host code to matrix and vector kernels (may need to add new method in the vector and matrix interfaces, as well as, CPU and RAJA implementations)

More specifically, in class `hiopFRProbSparse ` :
- Jacobian method
- `get_vars_info`, `get_cons_info` -> the type for loops
- `eval_f` -> for loop
- Hessian method

**Comment by nychiang** [comment]
fixed in PR #235
