### ISSUE TITLE
Copy eq and ineq to full size cons body/multipliers

### ISSUE THREAD

**Issue by cnpetra** [LLNL/hiop#233]
Externalize the host code to matrix and vector kernels (may need to add new method in the vector and matrix interfaces, as well as, CPU and RAJA implementations)

In class `hiopNlpFormulation`, the following functions only works on host:

1. `copy_EqIneq_to_cons`

2. `copy_cons_to_EqIneq` 

Need to move these functions into matrix/vector kernels.

**Comment by nychiang** [comment]
fixed in PR #235
