### ISSUE TITLE
timesMat segmentation fault

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#24]
Setting up three matrices like so:
```cpp
hiop::hiopMatrixDense A(M_global, K_global, k_partition, comm);
hiop::hiopMatrixDense M(K_global, N_global, n_partition, comm);
hiop::hiopMatrixDense W(M_global, N_global, n_partition, comm);
```
I then set values and attempt to call `timesMat`:
```cpp
A.setToConstant(A_val);
W.setToConstant(W_val);
M.setToConstant(M_val);
A.timesMat(beta, W, alpha, M);

real_type expected = (beta * W_val) + (alpha * A_val * M_val * N_global);
const int fail = verifyAnswer(&W, expected);
```
Which results in a segfault.

**Comment by cnpetra** [comment]
commits 5ba564148fd92148b8d26b0fc74251684bb3ffbd 30d1415eab7830b50e2db20783a78cca4e6e0968 c2c20df9340799dc7f5110ae38f3871737afef42 address this. The documentation of `timesMatTrans`, `timesMat`, and `transTimesMat` was also updated to better describe proper use of the methods

**Comment by cnpetra** [comment]
re: timesMat: see documentation https://github.com/LLNL/hiop/blob/e7e59b7f7d35141b21e67a2a488d664c03a344e1/src/LinAlg/hiopMatrix.hpp#L211

let me know if it does not make sense.

**Comment by ashermancinelli** [comment]
How should I set up matrices like you have mentioned? After your comment I tried setting the column partitions to null with no success.

**Comment by cnpetra** [comment]
do not pass communicator and partition info 
```
hiop::hiopMatrixDense A(M_local, K_local);
```
