### ISSUE TITLE
operator[] in hiopVectorIntRaja

### ISSUE THREAD

**Issue by cnpetra** [LLNL/hiop#243]
It looks like the `hiopVectorIntRaja ::operator[]` operators are not correctly implemented. They work with only the host buffer and have no sync capabilities.  

The following code will deceivingly output 3 but the actual data on device will be all zeros
```
hiopVectorIntRaja a(10);
a.setToZero();
a[2] = 3;
cout << a[2]; 
```

**Comment by cnpetra** [comment]
I am actually against offering the `[]` operators, but that is another discussion ...

**Comment by ashermancinelli** [comment]
The `copy(To|From)Dev` methods might be the sync capabilities you're looking for

**Comment by ashermancinelli** [comment]
I'm not against removing ` operator[]` in favor of something else fwiw

**Comment by cnpetra** [comment]
> The `copy(To|From)Dev` methods might be the sync capabilities you're looking for

cannot call the copy methods when working with the abstract hiopVectorInt type. An option is to add "synch-ing" methods in the abstract type, but it needs to be a bit more elaborate to avoid excessive "synch-ing"...

**Comment by pelesh** [comment]
> I am actually against offering the `[]` operators, but that is another discussion ...

I am not sure how operator overloading could be implemented in CUDA kernels. I think our best bet is to pass raw data arrays when accessing elements of the int vector on GPU. Having `[]` operator on the host is a nice convenience, but then it may create some confusion because you are accessing data differently on host than on device. When using unified memory space, the overloaded operator may cause some hidden host-device traffic.

**Comment by cnpetra** [comment]
> > I am actually against offering the `[]` operators, but that is another discussion ...
> 
> I am not sure how operator overloading could be implemented in CUDA kernels. I think our best bet is to pass raw data arrays when accessing elements of the int vector on GPU. Having `[]` operator on the host is a nice convenience, but then it may create some confusion because you are accessing data differently on host than on device. When using unified memory space, the overloaded operator may cause some hidden host-device traffic.

I suggest we make these operators private.

**Comment by nychiang** [comment]
@ashermancinelli  should we close this one as well?
