### ISSUE TITLE
`copyFrom` and similar methods are not part of the abstract hiopMatrix interface

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#25]
Heavy use is made of `copyFrom` and similar methods, yet the abstract interface does not mandate that a hiopMatrix implementation has this method. In contrast, hiopVector does have `copyTo` and `copyFrom` methods in the abstract interface. I believe this could lead to implementation-specific code which will cause problems when we attempt to migrate to other implementations for hiopMatrix.

**Comment by cnpetra** [comment]
I agree. will revisit hiopMatrix abstract class

another related todo would be to reconcile overloads of `addSubDiagonal`. in particular
```
void addSubDiagonal(const double& alpha, long long start_on_dest_diag, const hiopVector& d);
```
is redundant

**Comment by ashermancinelli** [comment]
If you don't get to this by next week I might take a stab at it, I know you've got a lot on your plate at the moment. Thanks!

**Comment by cnpetra** [comment]
on a closer inspection, it appears that `copyFrom` is specific to hiopDenseMatrix. I prefer to not push it up in the inheritance hierarchy to avoid confusion later on and since its functionality can be achieved via `new_copy`
