### ISSUE TITLE
Enable testing with srun

### ISSUE THREAD

**Issue by CameronRutherford** [LLNL/hiop#257]
Currently we support `jsrun` and `mpirun` as the testing commands, but we need to add support for `srun` in testing.

I doing so, there should be an equivalent option such as `HIOP_TEST_WITH_SLURM`, as well as making it a dependent option on other testing options (`HIOP_WITH_MAKETEST`, `HIOP_TEST_WITH_BSUB`).

cc @ashermancinelli

**Comment by ashermancinelli** [comment]
We will need this for testing on Spock, +1

**Comment by cnpetra** [comment]
any updates on this? Is this still needed?

**Comment by ashermancinelli** [comment]
CMake var `HIOP_CTEST_LAUNCH_COMMAND` resolves this.
