### ISSUE TITLE
DPOSVXEpsilon1Full parameter with illegal value

### ISSUE THREAD

**Issue by jmartfrut** [LLNL/hiop#27]
Hi,

I'm using hiop library together with  MFEM to solve a optimization problem that involves the resolution of a PDE. The optimization works very well and in few iteration a get convergence. However, I recieve the following warning after each iteration and I don't know what it means to be able to remove it.  

"On entry to DPOSVXEpsilon1Full parameter number  6 had an illegal value"

thanks for your time,
Jesus

**Comment by jmartfrut** [comment]
Sorry, I was using version v0.1 of Hiop. With version v0.2 the issue is solved.

**Comment by cnpetra** [comment]
good to hear
