### ISSUE TITLE
Options for constraint violation tolerance in line search

### ISSUE THREAD

**Issue by slmcbane** [LLNL/hiop#277]
In my own work, using Ipopt, I've discovered that the key to getting smooth convergence behavior is to control the constraint violation via the undocument options "theta_max_fact" and "theta_min_fact". See documentation for these options found [here](https://www.gams.com/latest/docs/S_IPOPT.html). I additionally make use of the option "watchdog_shortened_iter_trigger" to disable the watchdog procedure in my problem - I'm not sure if this heuristic is present in hiop at all.

I'd like to see these options added, and as my time allows I'll work on it myself. @cnpetra has already pointed me in the right direction in an email.

**Comment by cnpetra** [comment]
hiop does not support 'watchdog_shortened_iter_trigger`

**Comment by cnpetra** [comment]
let us know if you need help with either hiop or ipopt @nychiang

**Comment by slmcbane** [comment]
> 
> 
> hiop does not support 'watchdog_shortened_iter_trigger`

Is this because the watchdog procedure is not present at all, or just because the option is not implemented?

**Comment by nychiang** [comment]
> Is this because the watchdog procedure is not present at all, or just because the option is not implemented?

We don't have this heuristic procedure in HiOp.

**Comment by cnpetra** [comment]
> > Is this because the watchdog procedure is not present at all, or just because the option is not implemented?
> 
> We don't have this heuristic procedure in HiOp.

indeed, not present at this time but we can implement something similar or identical. What does it do ?

**Comment by slmcbane** [comment]
> What does it do?

If the first trial step has been rejected for _n_ consecutive iterations **and** the constraint violation is not too large, the watchdog heuristic essentially disables line search for the next iteration, reverting to the previous iterate if this doesn't result in progress to a point acceptable to the filter at the iterate where the watchdog was activated. I only use the setting in Ipopt to disable this procedure, so there's no need to spend effort on implementing it unless someone else believes it would be beneficial.
