### ISSUE TITLE
Update repo topics for RADIUSS

### ISSUE THREAD

**Issue by hauten** [LLNL/hiop#292]
@cnpetra & @acfisher

For HiOp to be included in https://software.llnl.gov/radiuss/, the repo topics under About need to have both `math-physics` and `radiuss`. As an LLNL org owner, I attempted to add the topics, but I got an error message saying a repo can't have more than 20. I hate to ask you to remove two other topics in order to add these two new topics, but that's how the catalog works: https://github.com/LLNL/llnl.github.io/blob/main/radiuss/README.md. A bot runs a couple times a day to update the catalog, so changes won't be reflected right away.

**Comment by cnpetra** [comment]
I made room for and added the two tags you mentioned.

**Comment by hauten** [comment]
Thanks! I will wait for the bot & then close the issue.
