### ISSUE TITLE
Pridecomp gradient is not divided by the number of recourse

### ISSUE THREAD

**Issue by jwang125** [LLNL/hiop#297]
This could be in conflict with how exago is implemented. Currently grad_r = \sum i=1^K \partial r_i, without dividing by K. This is consistent with how ex9 is implemented. Same for the rval, objective value.

**Comment by jwang125** [comment]
I will talk to Shri and confirm this is how exago is implemented and then it should be a quick fix.

**Comment by cnpetra** [comment]
Is the function value divided by the number of recourse terms?

**Comment by cnpetra** [comment]
closed by PR#299
