### ISSUE TITLE
Preprocessor logic for GPU-enabled linear solvers should return error if none is available

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#310]
In classes `hiopDualsLsqUpdateLinsysAugSparse` and `hiopKKTLinSysCompressedSparseXYcYd` preprocessor logic will look for GPU-enabled linear solver when user options other than "cpu" are enabled. In other words, if user selects "hybrid", "auto" or "gpu", the preprocessor directives will first try to use a GPU-enabled linear solver, but if none is available, they will fall back on a CPU-based solver. The code relies on unified memory to manage all host-device data transfers.

Consider returning error if user tries to use "hybrid" or "gpu" mode without GPU-enabled linear solver. I believe logic in HiOp user options already hides "hybrid" and "gpu" options from the user in cases when no GPU-enabled linear solver is available. Conflict between requested and available linear solvers in KKT linear system or duals updater would indicate a bug in options logic, so returning error here would be more appropriate than quietly falling back to a CPU linear solver. 

CC @kswyrido

**Comment by cnpetra** [comment]
re: `hiopDualsLsqUpdateLinsysAugSparse`, we want to leave the option of using CPU sparse linear solver for LSQ initialization (this is a "preprocessing" step) even when the `compute_mode` is `gpu` or `hybrid`. I think the preprocessor logic is doing exactly that.
