### ISSUE TITLE
build with cuSolver but without STRUMPACK

### ISSUE THREAD

**Issue by kswirydo** [LLNL/hiop#311]
Problem: while building with HIOP_USE_STRUMPACK OFF but HIOP_USE_CUSOLVER ON I am getting an error during `make`: make fails on the first file that requires CUDA. If both are on (STRUMPACK and CUSOLVER), it compiles ok.

Why this happens: somehow when STRUMPACK is ON, cuda includes are added to the compile commands. But even though cusolver explicitly links cuda and relevant libraries, they are not added to compile.

Not sure how to fix. 

branch: cusolver-rebase-dev.
@CameronRutherford @pelesh

**Comment by pelesh** [comment]
During the rebase, I needed to undo #295 to make this branch build. There seems to be a bug somewhere in CMake that affects setting CUDA dependencies, which I could not pinpoint. Current state of `cusolver-rebase-dev` branch is that we have a workaround to build and run it, but this is not ready for PR.

**Comment by ashermancinelli** [comment]
Could you further outline the issue? I'm sure @CameronRutherford  or myself could lend a hand with the cmake.

**Comment by CameronRutherford** [comment]
@ashermancinelli, @kswirydo and I went through this and #312 seems to be an appropriate workaround, although perhaps more discussion is warranted here for what the issue is, or in that PR for implementation details.

**Comment by kswirydo** [comment]
This has been fixed thanks @CameronRutherford

**Comment by kswirydo** [comment]
Fixed by Cameron.
