### ISSUE TITLE
Undefined handling of fixed variables in restoration

### ISSUE THREAD

**Issue by iaravena** [LLNL/hiop#335]
(related to #287)
I have encountered the following error message when trying to solve a problem that goes through restoration:

```
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
[Error] detected fixed variables but HiOp was not instructed how to deal with them (option 'fixed_var' is 'none').
```

which continues to appear even if `fixed_var` is specified through the interface or option file. Should the default be other value than `none`? How should options be set/modified for restoration?

**Comment by cnpetra** [comment]
that is strange, for now use `hiop_fr.options` and set `fixed_var` to `relax`

**Comment by nychiang** [comment]
try to set `fixed_var` to `relax` in both `hiop_fr.options` and `hiop.options`.
FR problem should not introduce fixed variables and all the fixed variables should come from the base problem.

**Comment by cnpetra** [comment]
yes, it's strange how it fails in FR without failing at initialization first.
