### ISSUE TITLE
Wrong inertia computation from MAGMA

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#336]
function [`magmablas_dsiinertia`](https://github.com/LLNL/hiop/blob/9c10190bbb0d54adf607b14986530f885788d77f/src/LinAlg/hiopLinSolverIndefDenseMagma.cpp#L142) returns unexpected value.

Has reported [this issue to MAGMA bitbucket](https://bitbucket.org/icl/magma/issues/54/inertia-computation-from-magma_dsytrf_gpu).

Note that correct inertia can be manually computed from the factorization factors, i.e., the outputs from `magma_dsytrf_gpu`. This implies that the factorization routine is correct, and something wrong with `magmablas_dsiinertia`.
@cnpetra  @pelesh @kswirydo

**Comment by cnpetra** [comment]
fixed by PR #414  as long as one sticks to magma master or next release (as of March 2022).
