### ISSUE TITLE
soft restoration

### ISSUE THREAD

**Issue by cnpetra** [LLNL/hiop#338]
there are cases where soft restauration is preferable and we should implement it in HiOp.

**Comment by nychiang** [comment]
Add a note:
soft FR fails in the contingence case of IEEE14 system, which is a SOCP problem.

**Comment by cnpetra** [comment]
@nychiang : not sure I follow...

**Comment by nychiang** [comment]
I add that note as a reminder for me. as it now works on the other cases, but failed in this easiest one.
