### ISSUE TITLE
Do *SymDenseMatrixUpperTriangle methods work for MPI partitioned matrices?

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#34]
It seems that `*SymDenseMatrixUpperTriangle` methods add elements of a rectangular matrix (pointed by `this`) into the upper triangular part of the matrix `W` (passed as the input argument). The methods use only _local_ data indices and may not work for distributed memory partitioned matrices unless the caller provides row and column start indices that would guarantee data is written to the upper triangular part of `W`.

It would be good to better document preconditions for calling these functions as they are nontrivial. Are these methods intended for use when both, none, or only `W` are MPI partitioned?

**Comment by cnpetra** [comment]
none of the parameters nor `this` should be distributed/partitioned. they're used beneath MPI. the fact that the linear algebra is used in two very different contexts (mpi for quasi-Newton solver and serial  for the Newton solver) is the main cause for having both partitioned and non-partitioned methods (and the source of confusion).

these methods needs to be documented better indeed, or even better, enforce the desired behavior through design/interface design (like subclass a "local" dense matrix)

**Comment by cnpetra** [comment]
functions documented - PR#41
