### ISSUE TITLE
Upgrade RAJA for CI tests

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#342]
In order to use RAJA::inclusive_scan, HiOp requires RAJA version 0.14 or greater. 

Some HiOp matrix/vector kernel functions need to be operated on the host. 
Using RAJA::inclusive_scan can help us to move all these computations to the device. 

@ashermancinelli Can you upgrade RAJA to the latest release? It should work with the `develop` branch. I will modify the files where I can use `RAJA::inclusive_scan`, and file another PR.

**Comment by nychiang** [comment]
@ashermancinelli  I created a branch, “raja-inclusive-scan-fix”, for you to test hiop with RAJA v0.14.
Let me know if you have issues to use RAJA v0.14. 
It seems that I need to add the following path to include CAMP:
`-I/g/g92/chiang7/software/lassen/raja/tpl/camp/include`
I am not sure why I cannot use the `include` folder from my local installation, e.g., "${RAJA_DIR}/include" with `RAJA_DIR=/g/g92/chiang7/software/lassen/raja/build/install`

**Comment by nychiang** [comment]
I just rebased all my existing branches and created a PR for branch `raja-inclusive-scan-fix`.
Now the branch architecture looks like:
`develop --- sparse-gpu-kernel-dev-3 --- sparse-gpu-kernel-dev-4 --- raja-inclusive-scan-fix`

I filed PR for the other two branches couple weeks ago, and they all come with some temporary fixes due to the `RAJA::inclusive_scan` issue. Between branch `raja-inclusive-scan-fix` and `sparse-gpu-kernel-dev-4`, only two files have been updated.

**Comment by ashermancinelli** [comment]
Has this been resolved? All CI is using raja 0.14.0 now.

**Comment by nychiang** [comment]
@ashermancinelli 
I can see all the tests work fine now with RAJA 0.14.0 (PR #347 )
Cheers!

**Comment by ashermancinelli** [comment]
Great to hear! Can this issue be closed then?

**Comment by nychiang** [comment]
I think this issue will be closed automatically with PR #347
