### ISSUE TITLE
HiOp dense matrix method assertSymmetry does not work with MPI partitioned matrices

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#35]
The method `hiopMatrixDense::assertSymmetry` checks symmetry of the local data block and likely won't work with distributed memory partitioned matrices. It would be good to clarify this in the documentation.

**Comment by cnpetra** [comment]
this is a debug function (available only under `DEEP_CHECKS`). Should be used only for non-distributed matrices. I guess should assert(false); and return false for distributed matrices.
