### ISSUE TITLE
Cannot specify link libraries for target "nlpHybrid_ex6.exe" which is not built by this project.

### ISSUE THREAD

**Issue by shakedregev** [LLNL/hiop#350]
Created a new [file](https://github.com/LLNL/hiop/blob/shaked_hybrid/src/Drivers/nlpHybrid_ex6_driver.cpp) to copy the existing functionality. I edited [CMakeLists](https://github.com/LLNL/hiop/blob/shaked_hybrid/src/Drivers/CMakeLists.txt#L46) in the same folder.

The obvious answer when I saw this error, is look in the project for where the other object is specified to be built. Unfortunately, I searched the file and the repo and could not find it. Any tips?

@kswirydo @pelesh

**Comment by nychiang** [comment]
change your line  from
add_executable(nlpSparse_ex6.exe nlpSparse_ex6.cpp nlpHybrid_ex6_driver.cpp)
to
add_executable(nlpHybrid_ex6.exe nlpSparse_ex6.cpp nlpHybrid_ex6_driver.cpp)

**Comment by shakedregev** [comment]
I can't believe I missed that. Thanks!
