### ISSUE TITLE
Warning about invalid option for 'KKTLinsys', but option is valid

### ISSUE THREAD

**Issue by shakedregev** [LLNL/hiop#354]
[Warning] Hiop: value 'HybridCholCG' for option 'KKTLinsys' must be one of [ auto xycyd xdycyd full HybridCholCG ]. Default value 'auto' will be used. You can see changes [here](https://github.com/LLNL/hiop/blob/shaked_hybrid/src/Utils/hiopOptions.cpp#L770)

**Comment by cnpetra** [comment]
when you add 'HybridCholCG' in `vector<string> range(4)`, please make sure it is all lower case, `range[4]="hybridcholcg";

**Comment by shakedregev** [comment]
That worked, thanks
