### ISSUE TITLE
Added file describing examples 6 and 7

### ISSUE THREAD

**Issue by shakedregev** [LLNL/hiop#355]
No resolution needed, but might be useful.
[HiOp_examples6+7.pdf](https://github.com/LLNL/hiop/files/7470642/HiOp_examples6%2B7.pdf)

**Comment by cnpetra** [comment]
it would be nice to add it to the documentation. Open a PR if you have the chance to discuss where to place it. Or email me the tex file and I can take care of it.

**Comment by shakedregev** [comment]
Emailed

**Comment by cnpetra** [comment]
thank you. it has been added under `doc`
