### ISSUE TITLE
Hessian hardwired as diagonal in sparse case?

### ISSUE THREAD

**Issue by shakedregev** [LLNL/hiop#356]
Have a look [here](https://github.com/LLNL/hiop/blob/shaked_hybrid/src/Drivers/nlpSparse_ex6b.cpp#L196). I tried to create a Hessian with a non-diagonal term (for testing), but I got a segfault. Is there somewhere where the size of the Hessian is hardwired?

Basically I just added +$x_1 * x_2$ to the objective to make things a little more interesting.

**Comment by cnpetra** [comment]
make sure you return the correct sizes (matrix dim and nnz) in [`get_sparse_blocks_info`](https://github.com/LLNL/hiop/blob/68ee003d968e07c3710d2b8466c80f88f0a55af5/src/Drivers/nlpSparse_ex6b.cpp#L59)

Also, don't forget to update the gradient callback...

**Comment by shakedregev** [comment]
Thanks, the dimension is unchanged. I increased nnz by 1 and added a print statement just to verify that it's indeed happening (it is). But I am still getting a segfault. Is there somewhere else I need to set this?

Also, I changed the gradient (but there are no new nonzeros)

**Comment by shakedregev** [comment]
This is the difference between my file and the original
```
>   gradf[0]+=x[1];
>   gradf[1]+=x[0];
192,194d195
<     //Note: lambda is not used since all the constraints are linear and, therefore, do
<     //not contribute to the Hessian of the Lagrangian
<     assert(nnzHSS == n);
195a197,199
>     iHSS[0] = jHSS[0] = 0;
>     iHSS[1] = 0;
>     jHSS[1] = 1;
197c201,203
<       for(int i=0; i<n; i++) iHSS[i] = jHSS[i] = i;
---
>       for(int i=1; i<n; i++){
>         iHSS[i+1] = jHSS[i+1] = i;
>       }
201c207,211
<       for(int i=0; i<n; i++) MHSS[i] = scal * obj_factor * 3*pow(x[i]-1., 2);
---
>       MHSS[0]= scal * obj_factor * 3*pow(x[0]-1., 2);
>       MHSS[1]=1.0;
>       for(int i=1; i<n; i++){
>         MHSS[i+1] = scal * obj_factor * 3*pow(x[i]-1., 2);
>       }
```

**Comment by nychiang** [comment]
[I see an out of bounds error in Line 201.
](https://github.com/LLNL/hiop/blob/0819c2c392484ad99fbf3f64dec815b8c591e1f5/src/Drivers/nlpSparse_ex6b.cpp#L201)

Change this for loop to:
```
for(int i=2; i<n; i++) {
  iHSS[i] = jHSS[i] = i-1;
}
```

**Comment by shakedregev** [comment]
But this means iHSS and jHSS have size n, which is not what I want. I want them with size n+1.

**Comment by nychiang** [comment]
@shakedregev you are correct.
I guess the easiest to find this bug is to use valgrind, or run a gdb session.
Try to run `valgrind nlpHybrid_XXXXXX`

**Comment by shakedregev** [comment]
We resolved this, it was an issue of the method being called before it is actually used, so the checks about the arrays not being null are important.
