### ISSUE TITLE
Protected members between sibling classes

### ISSUE THREAD

**Issue by shakedregev** [LLNL/hiop#357]
I now need to explicitly symmetrize my Hessian (forget what I said earlier, figuring out the right scaling is difficult if only the upper triangular part of matrix is stored, so I need it for scaling). You can see my prototype [here](https://github.com/LLNL/hiop/blob/shaked_hybrid/src/LinAlg/hiopMatrixSparseTriplet.hpp#L335) and the function I started [here](https://github.com/LLNL/hiop/blob/shaked_hybrid/src/LinAlg/hiopMatrixSparseTriplet.cpp#L965). Maybe there is a better way to do this.

**Comment by cnpetra** [comment]
Looks good. I suggest using a method name (like "new_symm_copy)" that makes it explicit a new matrix is created.

Also, I would rely on std::sort to reorder the entries, you implementation is quite inefficient... there are code style discrepancies (see https://github.com/LLNL/hiop/blob/develop/README_developers.md), but I guess they will be fixed later.
