### ISSUE TITLE
HiOp Output -- Getting scaled values for objective and lagrange multipliers instead of actual values

### ISSUE THREAD

**Issue by abhyshr** [LLNL/hiop#360]
HiOp version: 0.5.1

When retrieving the objective value and lagrange multipliers from the `solution_callback` method, I am getting scaled values instead of the actual values.

The optimization iterations report: 
```
...
11  4.1444571e+03 1.386e-04  4.665e-02  -3.82  1.000e+00  8.975e-01  1(s)
  12  4.1444631e+03 2.127e-05  1.166e-04  -3.82  1.000e+00  1.000e+00  1(s)
  13  4.1444512e+03 1.194e-05  4.263e-03  -5.73  1.000e+00  9.504e-01  1(s)
  14  4.1444510e+03 3.441e-06  9.050e-06  -5.73  1.000e+00  1.000e+00  1(h)
  15  4.1444508e+03 6.325e-07  1.699e-06  -7.00  1.000e+00  1.000e+00  1(h)
  16  4.1444508e+03 6.484e-08  2.087e-07  -7.00  1.000e+00  1.000e+00  1(h)
Successfull termination.
Total time 0.003 sec 
...
```

while the objective value from `solution_callback` is 
```
Breakpoint 2, OPFLOWHIOPInterface::solution_callback (this=0x10c54e90, status=hiop::Solve_Success, n=24, 
    xsol=0x10c5b6c0, z_L=0x10c5be50, z_U=0x10c5bf60, m=36, gsol=0x10c64400, lamsol=0x10c64290, 
    obj_value=143.35699621745647) at /people/abhy245/projects/exaSGD/exago/src/opflow/solver/hiop/opflow-hiop.cpp:272
272	  opflow->obj = obj_value;
(gdb) p obj_value
$1 = 143.35699621745647
```
The scaled objective value 143.35699621745647 is being returned in `solution_callback` rather than the actual value 4.1444508e+03. The scaling factor is `obj_factor` passed to the Hessian routine.

You can reproduce this with ExaGO
```
./opflow -netfile ../../datafiles/case9/case9mod.m -opflow_genbusvoltage VARIABLE_WITHIN_BOUNDS -print_output -opflow_initialization ACPF -hiop_compute_mode CPU -opflow_solver HIOP -opflow_model POWER_BALANCE_HIOP -hiop_verbosity_level 3
```

Let me know if you need any other info.

@cnpetra @nychiang @ashermancinelli

**Comment by abhyshr** [comment]
Digging a bit more, I found that we are no longer setting the option `scaling_type` to `none`. Should I be rescaling the values in `solution_callback` or is this something you plan to add to HiOp?

**Comment by nychiang** [comment]
I think this should be corrected from the HiOp end.
@cnpetra agree?

**Comment by cnpetra** [comment]
I agree, this is an inconsistency we need to fix on HiOp's end.

**Comment by cnpetra** [comment]
> Digging a bit more, I found that we are no longer setting the option `scaling_type` to `none`. Should I be rescaling the values in `solution_callback` or is this something you plan to add to HiOp?

no rescaling is needed, after PR #366 HiOp going to give you the rescaled objective in the callback functions.

The scaling of the Lagrange multipliers works as supposed and no changes are needed in your code nor in HiOp.

**Comment by cnpetra** [comment]
it appears that the multipliers are not always scaled back correctly. @nychiang @abhyshr

**Comment by cnpetra** [comment]
we need to rescale the multipliers both in the user callbacks and in `get_solution`
