### ISSUE TITLE
ExaGO failure with HIOP

### ISSUE THREAD

**Issue by abhyshr** [LLNL/hiop#376]
I am seeing a divergence of Stochastic OPF (SOPFLOW) when the initial guess for the solver is changed. This is with HiOp NewtonMDS on the CPU and with HIOPSPARSE. The command to run is:
 
```
./sopflow -netfile ../share/exago/datafiles/case_ACTIVSg200.m -scenfile $EXAGO_DIR/datafiles/10_scenarios_ACTIVSg200.csv -sopflow_solver HIOP -sopflow_Ns 2 -opfflow_initialization ACPF -opflow_ignore_lineflow_constraints 1 -sopflow_subproblem_solver HIOP -sopflow_subproblem_model POWER_BALANCE_HIOP -hiop_compute_mode CPU -hiop_verbosity_level 3 -sopflow_mode 1 -sopflow_Nc 0 -sopflow_Ns 3 -opflow_initialization ACPF
 ```
Change to -opflow_subproblem_solver HIOPSPARSE -opflow_subproblem_model POWER_BALANCE_POLAR to switch to using Hiop sparse solver.
 
Here's what the output for a subproblem looks like before it hangs.
 
```
Total number of inequality constraints: 0
     lower/upper/lower_and_upper bounds: 0 / 0 / 0
iter    objective     inf_pr     inf_du   lg(mu)  alpha_du   alpha_pr linesrch
   0  2.7460238e+04 1.219e-02  2.321e+03  -1.00  0.000e+00  0.000e+00  -(-)
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Failed to read option file 'hiop_fr.options'. Hiop will use default options.
[Warning] Unusually large bound dual variables (norm1=1.07549e+272) occured, which may cause numerical instabilities if it persists. Convergence  issues or inacurate optimal solutions may be experienced. Possible causes:  tight bounds or bad scaling of the optimization variables.
[Warning] For example, increase 'fixed_var_tolerance' to relax aditional (tight) variables and/or increase 'fixed_var_perturb' to decrease the tightness.
   1  2.7640952e+04 2.101e-02  1.075e+272  -1.00  1.000e+00  1.000e+00  0(R)
[Warning] hiopLinSolverIndefDense error: 828 entry in the factorization's diagonal
is exactly zero. Division by zero will occur if it a solve is attempted.
[Warning] hiopLinSolverIndefDense error: 828 entry in the factorization's diagonal
is exactly zero. Division by zero will occur if it a solve is attempted.
[Warning] Unusually large bound dual variables (norm1=1.07548e+272) occured, which may cause numerical instabilities if it persists. Convergence  issues or inacurate optimal solutions may be experienced. Possible causes:  tight bounds or bad scaling of the optimization variables.
[Warning] For example, increase 'fixed_var_tolerance' to relax aditional (tight) variables and/or increase 'fixed_var_perturb' to decrease the tightness.
   2  3.2029152e+04 1.826e-03  1.075e+272  -1.00  3.647e-265  2.034e-269  1(s)
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Failed to read option file 'hiop_fr.options'. Hiop will use default options.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
Panic: minimum step size reached. The problem may be infeasible or the gradient inaccurate. Try to restore feasibility.
 ```
When -opflow_initialization is changed to MIDPOINT, HIOP is able to converge successfully. So, I am wondering what could be going on here since only the initial guess is being changed.

@nychiang

**Comment by abhyshr** [comment]
> I use the following command:
`./sopflow -netfile ../share/exago/datafiles/case_ACTIVSg200.m -scenfile ../share/exago/datafiles/10_scenarios_ACTIVSg200.csv -sopflow_solver HIOP -sopflow_Ns 2 -opfflow_initialization ACPF -opflow_ignore_lineflow_constraints 1 -sopflow_subproblem_solver HIOPSPARSE -sopflow_subproblem_model POWER_BALANCE_POLAR -hiop_compute_mode CPU -hiop_verbosity_level 3 -sopflow_mode 1 -sopflow_Nc 0 -sopflow_Ns 3 -opflow_initialization ACPF`
 
> The hightlighted ones are different from the ones you mentioned in Github, i.e., ` -opflow_subproblem_solver HIOPSPARSE -opflow_subproblem_model POWER_BALANCE_POLAR`.
 
> I think mine usage is correct, but, the `bad` news is that I cannot reproduce this failure. All the master/recourse cases are fine and I can reach the final convergence.

My apologies for the typo. The command you have above is correct for HIOPSPARSE solver. I am also getting a converged solution when using `HIOPSPARSE`. I probably had a typo somewhere in the earlier command.

So, the only solver for which I am getting divergence currently is with the HIOP MDS solver
`./sopflow -netfile ../share/exago/datafiles/case_ACTIVSg200.m -scenfile ../share/exago/datafiles/10_scenarios_ACTIVSg200.csv -sopflow_solver HIOP -opflow_ignore_lineflow_constraints 1 -sopflow_subproblem_solver HIOP -sopflow_subproblem_model POWER_BALANCE_HIOP -hiop_compute_mode CPU -hiop_verbosity_level 3 -sopflow_mode 1 -sopflow_Nc 0 -sopflow_Ns 3 -opflow_initialization ACPF`

**Comment by abhyshr** [comment]
I am working on debugging it right now. will send you a note if I find anything.

**Comment by abhyshr** [comment]
I've created a new branch for ExaGO `sopflow/debug-hiop-acpf-divergence` to debug this divergence issue (made a small change to variable bounds to make the models same). The attached files have the variable bounds and x0 with different solvers and initialization type. 
x0_hiop_midpoint.txt -- x0 (and bounds) when using hiop MDS solver with MIDPOINT initialization.
x0_hiop_acpf.txt -- Same with ACPF initialization
x0_ipopt_midpoint.txt -- x0 (and bounds) when using IPOPT solver
x0_hiop_acpf.txt -- Same with ACPF initialization

[x0_hiop_midpoint.txt](https://github.com/LLNL/hiop/files/7720412/x0_hiop_midpoint.txt)
[x0_hiop_acpf.txt](https://github.com/LLNL/hiop/files/7720414/x0_hiop_acpf.txt)
[x0_ipopt_acpf.txt](https://github.com/LLNL/hiop/files/7720415/x0_ipopt_acpf.txt)
[x0_ipopt_midpoint.txt](https://github.com/LLNL/hiop/files/7720416/x0_ipopt_midpoint.txt)

I did a diff on both the _midpoint.txt files and it shows there is no difference. Same for the _acpf.txt files. So, from what I can tell the same x0 and bounds are being passed to hiop and ipopt solvers. HIOP diverges while IPOPT gives a successful solution.

**Comment by nychiang** [comment]
It seems this bug has been fixed in the latest release of HiOp. 
Please confirm and we can close this issue. @abhyshr
