### ISSUE TITLE
Casting error in hiopInterface.hpp

### ISSUE THREAD

**Issue by andersp** [LLNL/hiop#382]
When compiling my interface routines I get the following error after including hiopInterface.hpp:

/Users/petersson1//include/hiopInterface.hpp:250:60: error: static_cast from 'void *' to 'int' is not allowed
  virtual bool get_MPI_comm(MPI_Comm& comm_out) { comm_out=MPI_COMM_WORLD; return true;}

I looked in hiopMPI.hpp and it looks like MPI_Comm is defined to be an int. Shouldn't it be a 'void *' ?

**Comment by jwang125** [comment]
It is an int only if MPI is not defined and we use int to substitute MPI_Comm in the code. And MPI_COMM_WORLD in this case would be 0, an int value.

**Comment by andersp** [comment]
That is obviously not true in this case because the compiler complains about a casting error. In my case, I am only using hiop in serial, but my code uses MPI to compute the objective and its gradient. Would it help to build hiop with -DHIOP_USE_MPI=On ?

**Comment by jwang125** [comment]
That was the intention at least. It should because then MPI_COMM will just be defined by mpi.h. Let me know if that works.

**Comment by cnpetra** [comment]
yes, use `-DHIOP_USE_MPI=ON` 

you also need to set up HiOp to run on one process only in your parallel simulation, pm me/us if you need help.

We will fix the casting error, it occurs only with ompi... mpich defines MPI_Comm as an int if I recall correctly...

**Comment by cnpetra** [comment]
We looked into this and there is not much we can do to fix the issue on HiOp's end. Apparently, the error you report for non-MPI HiOp build occurs because you include `mpi.h` after `hiopInterface.hpp` so HiOp defines the MPI surrogate types. Including HiOp header after the MPI header should fix this. Or even better, use `-DHIOP_USE_MPI=ON`

**Comment by andersp** [comment]
I just checked my code. I include hiopInterface.hpp after mpi.h, so there should be no reason for HiOp to define MPI surrogates. 
I can build my code if I first build HiOp with -DHIOP_USE_MPI=ON, but the optimizer fails to find a good solution. I will stick with Ipopt for now.
