### ISSUE TITLE
error in the dense factorization

### ISSUE THREAD

**Issue by andersp** [LLNL/hiop#387]
When using HiOp on the LC cluster quartz, I get the following error:
.../hiopAlgFilterIPM.cpp:1188: hiop::hiopSolveStatus hiop::hiopAlgFilterIPMQuasiNewton::run(): Assertion `bret' failed.

Any idea whats going on?

**Comment by nychiang** [comment]
Can you create a file `hiop.options` at the folder where you run your code, which includes the following lines:
```
print_options yes
verbosity_level 4
```
hiop should give us more details under this setting.
Can you save the output and send it to us?

Thanks,

**Comment by andersp** [comment]
[hiop-out.txt](https://github.com/LLNL/hiop/files/7811986/hiop-out.txt)
Here is the output I got from the run.

**Comment by nychiang** [comment]
Can you try the following parameters:
```
duals_update_type linear 
duals_init zero
```

**Comment by andersp** [comment]
Now it works. Thanks!
