### ISSUE TITLE
Consider using conditionals instead of preprocessor directives in function `do_lsq_update`

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#417]
The logic for selecting linear solver in function `hiopDualsLsqUpdateLinsysAugSparse::do_lsq_update` in file `hiopDualsUpdater.cpp` is implemented as combination of preprocessor directives and conditional statements. Consider replacing preprocessor directives with conditionals where arguments are constant expressions from structure `hiopVersion`. For example, replace
```c++
#ifdef HIOP_USE_GPU
  ...
#endif
```
with
```c++
if(hiopVersion::useGPU) {
  ...
}
```
Eliminating preprocessor directives could make code more readable and easier to debug/maintain.

CC @ashermancinelli

**Comment by cnpetra** [comment]
logic should be more clear now that the "logic" code is much compact (PR #441).
