### ISSUE TITLE
Add option to use cusolverRfRefactor instead of GLU refactorization in cuSOLVER

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#429]
Function `cusolverRfRefactor` and related functions from cuSOLVER library allow access to LU factors needed for custom implementation of iterative refinement. Equivalent GLU functions from the same library, while showing better performance, do not provide the same access to the intermediate objects during matrix factorization.

It would be good to provide option in cuSOLVER-LU interface in HiOp for user to select GLU or `cusolverRfRefactor` refactorization. This will also enable development of custom GPU-based iterative refinement techniques for HiOp.

Blocks #430 

@cnpetra @nychiang

**Comment by pelesh** [comment]
Following @nychiang's comments in #427, it would be good to have refactor routine return info on matrix singularity. As far as I can see, there is a function 
```c++
cusolverStatus_t
cusolverRfSetNumericProperties(cusolverRfHandle_t handle,
                               double zero,
                               double boost);
```
that is regularizing matrix (boosting pivots). My understanding is that `zero` is the threshold when boosting is done and `boost` is the regularization of the pivot. HiOp could get info if the zero threshold was reached through function
```c++
cusolverStatus_t
cusolverRfGetNumericBoostReport(cusolverRfHandle_t handle,
                                cusolverRfNumericBoostReport_t *report);
```
It seems the only way to get an information whether matrix is singular is to do some regularization by setting a nonzero `boost` in `cusolverRfSetNumericProperties`.

The refactor routines do not have LAPACK-style interface with "info" integer that returns code about issues encountered.

**Comment by cnpetra** [comment]
> ```c++
> cusolverRfSetNumericProperties
> ```

looks like that would do it. What are the default values for  `boost` and `zero` (when  `Set...` is not called) ?

**Comment by pelesh** [comment]
This functionality was added as a part of refactoring cuSOLVER interface in #427.
