### ISSUE TITLE
Magma interface implementation in hiopLinSolver.hpp

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#43]
Magma solver interface is implemented in `hiopLinSolver.hpp` what seems to pollute HiOp API. One consequence of that is that any application depending on HiOp will depend on Magma API and will need Magma include files to build (if HiOp is built with Magma). Perhaps it would be good idea to move the implementation of Magma interface to a separate compilation unit (a `*.cpp` file)?

@cnpetra @ashermancinelli

**Comment by cnpetra** [comment]
on my todo list

**Comment by cnpetra** [comment]
addressed by PR#51
