### ISSUE TITLE
Add iterative refinement for LU linear solver from cuSOLVER library

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#430]
Implement iterative refinement on GPU for the LU-based direct solver from cuSOLVER library. GPU direct solvers do not always produce high quality solution and the iterative refinement may be an efficient way to address that.

@cnpetra @nychiang

**Comment by nychiang** [comment]
@pelesh  FYI, there are two ways to do iterative refinement (IR):
IR_1. based on full KKT residual, do FR (solve compressed system, calculate the values for other variables, and re-evaluate the full KKT residual)
IR_2. based on compressed system residual, e.g., XDYcYd, do IR (solve compressed system and re-evaluate the compressed KKT residual)

I think you and @kswirydo want to implement IR_2, and it can be an update for your existing cuSolver code. For example, ma57dd solves the linear system with IR, while ma57cd solves the same system without IR.
On the other hand, IR_1 has been implemented in PR #422, using BiCGStab mechanism to refine the solution.
