### ISSUE TITLE
Consider using compile-time instead of run-time polymorphism for implementing CSR matrix classes

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#437]
HiOp's base sparse matrix class has ~40 pure virtual methods. Classes inheriting from it represent symmetric or general matrices that can be stored in triplet or CSR format with member methods implemented as sequential or thread parallel using RAJA. It is expected that more sparse matrix classes will be added in the future and there is a need to manage the complexity of the linear algebra implementation in HiOp. Because of current inheritance structure, when adding a new method to one sparse matrix class, all other sparse matrix classes need to be updated accordingly, even if they don't use that method. This raises concerns about future maintenance cost for HiOp.

Consider using compile time polymorphism and function overloading (similar to STL) instead of virtual inheritance to manage more effectively multiple variants of sparse matrices and other linear algebra objects in HiOp. The objective is to:
- Make clean separation between HiOp functions and hardware backend implementations to allow simple way of adding new hardware backends and new matrix types.
- Simplify class inheritance structure for sparse matrices.
- Provide means in the code to simplify user selection of linear algebra/hw backend
- Be minimally invasive to avoid larger scale refactoring of HiOp code

**Comment by pelesh** [comment]
### Short term

Following can be addressed within #436:

Create class template for CSR matrix class inheriting from the base sparse matrix class like this:
```c++
/// @file MatrixSparseCSR.hpp
#include "MatrixSparse.hpp"

template <class T>
class MatrixSparseCSR : public MatrixSparse, T
{
public:
  MatrixSparseCSR(double a);
  virtual ~MatrixSparseCSR(){}

  virtual void hiopSetMatrixZero() override;
  ...

private:
  double a_;
  int nnz_;
  ...

}
``` 
Here template parameter `T` is an execution policy. The implementation of matrix kernels is in header file:
```c++
///  @file MatrixSparseCSRImpl.hpp
template<class T>
void MatrixSparseCSR<T>::hiopSetMatrixZero()
{
  std::cout << ID_STRING << "\n";
  T::setMatrixZero(&a_, nnz_);
}

...
```
In this file HiOp specific details are specified such as extracting data pointers and checking object sizes. These should be common for all CSR classes regardless of hardware backend they use. Actual computation is done in the execution policy class `T`. The policies contain "bare bones" kernels (BLAS-like) that take only simple data types for arguments:
```c++
/// @file CudaPolicy.hpp
namespace csr {
class CudaPolicy
{
public:
    CudaPolicy() = default;
    ~CudaPolicy() = default;

    void setMatrixZero(double* vals, int nnz)
    {
        // implementation here
    }

...
};
} // namespace csr
```
Specific template instance is completed by implementing source file
```c++
/// @file MatrixSparseCSRCuda.cpp
#include "MatrixSparseCSR.hpp"
#include "CudaPolicy.hpp"

#define ID_STRING "Template using CUDA policy ..."

template<class T>
MatrixSparseCSR<T>::MatrixSparseCSR(double a) : a_(a)
{
  // constructor implementation
}

#include "MatrixSparseCSRImpl.hpp"
template MatrixSparseCSR<csr::CudaPolicy>::MatrixSparseCSR(double a);
```
This file contains only some preprocessor directives and functions such as constructors, specific for this template instance.

The short-term solution:
- Provides clean separation between hardware-specific kernels and HiOp-specific objects.
- Slightly reduces overall code size as it keeps code common for all variants of CSR matrix class in `MatrixSparseCSRImpl.hpp` file.
- CSR matrix still has the same sparse matrix interface as other sparse matrix classes currently in HiOp.

### Next step

Beyond #436, once the CSR matrix template is implemented and tested, the existing triplet sparse matrix classes can be folded into this template, as well, by simply creating triplet policies in a different namespace
```c++
/// @file CudaPolicy.hpp
namespace triplet {
class CudaPolicy
{
public:
    void setMatrixZero(double* vals, int nnz)
    {
        // triplet implementation here
    }
...
};
} // namespace triplet
```
and creating template instance like this:
```c++
/// @file MatrixSparseTripletCuda.cpp
#include "MatrixSparse.hpp"
#include "TripletCudaPolicy.hpp"

template<class T>
MatrixSparse<T>::MatrixSparse(double a) : a_(a)
{
  // constructor implementation
}

#include "MatrixSparseImpl.hpp"
template MatrixSparse<triplet::CudaPolicy>::MatrixSparse(double a);
```
This also eliminates the need for pure virtual sparse matrix class as all matrix sparse matrix variants are obtained by selecting execution policy template parameter. This could also allow us to remove most of 40-something sparse matrix class methods  and implement them as standalone functions in `hiop` namespace. Instead of inheritance, we can now use simply function overloading to ensure optimization algorithms  remain agnostic of sparse matrix type.
```c++
/// @file MatrixSparseCSRSeqOperators.hpp
namespace csr {
void matrixMatrixMultiplySparse(const MatrixSparseCSR<csr::SeqPolicy>& m1,
                                const MatrixSparseCSR<csr::SeqPolicy>& m2,
                                MatrixSparseCSR<csr::SeqPolicy>& result)
{
    // CSR matrix sequential implementation here ... 
}
} // namespace csr
```
 This should make linear algebra easier to extend, especially when dealing with kernels specific to a template instance. It may also allow HiOp users to add their functionality extensions, if needed, without modifying HiOp code.

**Comment by pelesh** [comment]
### Long term

Using this approach, you could let user select the execution policy by passing as a template parameter like this:

```c++
hiopNlpSparse<csr::CudaPolicy> nlp(nlp_interface);
```
This would simplify managing options in HiOp and give user more control on execution on different hardware. For example, in our RAJA implementation we hard-wire block size to 256 threads because we don't have a convenient way for user to set it. With minor modification to `CudaPolicy` we could have something like
```c++
hiopNlpSparse<csr::CudaPolicy<256>> nlp(nlp_interface);
```
allowing user to select block size tailored to user's problem.

The nonlinear problem formulation class would in that case be slightly modified to be a class template with execution policy as the parameter. Setting default to be sequential triplet sparse matrix would leave default user experience unchanged from what it is now. 
```c++
template <class T=triplet::Seq>
class hiopNlpSparse : public hiopNlpFormulation
{
public:
 ...
private:
  Matrix<T> A_;
};
```

**Comment by ashermancinelli** [comment]
LGTM, however I prefer we not inherit from the exec policy. We can just keep it wrapped up as an inner type alias and keep all it's methods static. I can't think of a reason we should need an _instance_ of the exec delegate. [Here's a more flushed out example of what I mean](https://godbolt.org/z/3P9TKvff9).

**Comment by cnpetra** [comment]
closing this based on offline discussions.
