### ISSUE TITLE
Sparse Example 2 fails with Ginkgo linear solver

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#469]
Sparse Example 2 (formerly Example 7), a nonconvex optimization problem, fails when using Ginkgo solver. The failure is triggered by assertion statement checking if `zl->matchesPattern(nlp->get_ixl())`. Complete error output is below. The same issue happens at all CI pipelines. 

```shell
25: Test command: /share/apps/openmpi/4.1.0mlx5.0/gcc/9.1.0/bin/mpirun "-n" "1" "/people/svcexasgd/gitlab/94827/build/src/Drivers/Sparse/NlpSparseEx2.exe" "500" "-ginkgo" "-inertiafree" "-selfcheck"
25: Test timeout computed to be: 1800
25: [1652233729.094246] [dlt08:147274:0]       ib_iface.c:665  UCX  ERROR ibv_create_cq(cqe=4096) failed: Cannot allocate memory
25: [dlt08.local:147274] pml_ucx.c:273  Error: Failed to create UCP worker
25: ===============
25: Hiop SOLVER
25: ===============
25: Using 1 MPI ranks.
25: ---------------
25: Problem Summary
25: ---------------
25: Total number of variables: 500
25:      lower/upper/lower_and_upper bounds: 499 / 1 / 1
25: Total number of equality constraints: 2
25: Total number of inequality constraints: 499
25:      lower/upper/lower_and_upper bounds: 498 / 498 / 497
25: iter    objective     inf_pr     inf_du   lg(mu)  alpha_du   alpha_pr linesrch
25:    0  6.4379656e+01 9.980e+00  1.010e+00   0.00  0.000e+00  0.000e+00  -(-)
25: Symbolic nonzero: 6498
25: Number of levels: 5
25: Device 0: NVIDIA GeForce RTX 2080 Ti has been selected.
25: Gaussian elimination with static pivoting (GESP)...
25: 1-Norm of A matrix is 501.002, Perturbation value is 5.01002e-06
25: Total GPU time: 1.18659 ms
25: [Warning] BiCGStab did NOT converged after 9 iters. The solution from iter 9 was returned.
25: 	 - Error code 1
25: 	 - Abs res=nann	 - Rel res=nan
25: 	 - ||rhs||_2=22248.7   ||sol||_2=nan
25: [Warning] Requesting additional accuracy and stability from the KKT linear system at iteration 0 (safe mode ON) [2]
25: Device 0: NVIDIA GeForce RTX 2080 Ti has been selected.
25: Gaussian elimination with static pivoting (GESP)...
25: 1-Norm of A matrix is 501.002, Perturbation value is 5.01002e-06
25: Total GPU time: 0.959936 ms
25: [Warning] BiCGStab did NOT converged after 9 iters. The solution from iter 9 was returned.
25: 	 - Error code 1
25: 	 - Abs res=nann	 - Rel res=nan
25: 	 - ||rhs||_2=nan   ||sol||_2=nan
25: Minimum step size reached. The problem may be locally infeasible or the gradient inaccurate. Will try to restore feasibility.
25: NlpSparseEx2.exe: /people/svcexasgd/gitlab/94827/src/Optimization/hiopIterate.cpp:381: virtual bool hiop::hiopIterate::takeStep_duals(const hiop::hiopIterate&, const hiop::hiopIterate&, const double&, const double&): Assertion `zl->matchesPattern(nlp->get_ixl())' failed.
25: [dlt08:147274] *** Process received signal ***
```

**Comment by pelesh** [comment]
@fritzgoebel, please take look.

**Comment by nychiang** [comment]
set `ir_outer_maxit` to `0`

**Comment by cnpetra** [comment]
> set `ir_outer_maxit` to `0`

@pelesh @fritzgoebel : add a line with `ir_outer_maxit 0` in the `hiop.options` file and see if the error is still present. Just to rule out iterative refinement as a potential source for the error.

**Comment by fritzgoebel** [comment]
@pelesh I looked at the matrix this example produces and the U factor GLU computes for this example is singular. Since we have not yet completed the implementation of our own factorization, we currently interface GLU to be able to provide an interface to direct solvers in Ginkgo. This will ultimately be replaced with our own direct solver that will hopefully be able to solve problems like this one.

**Comment by pelesh** [comment]
> @pelesh I looked at the matrix this example produces and the U factor GLU computes for this example is singular. Since we have not yet completed the implementation of our own factorization, we currently interface GLU to be able to provide an interface to direct solvers in Ginkgo. This will ultimately be replaced with our own direct solver that will hopefully be able to solve problems like this one.

Would it be possible to return information on matrix singularity to HiOp, so it can try to regularize the matrix for you? That could be a good temporary solution, it it is not too difficult to add.

**Comment by fritzgoebel** [comment]
Sure, I will see on Monday if this is easily doable with the information I get from GLU.
