### ISSUE TITLE
compilation error when klu is missing

### ISSUE THREAD

**Issue by cnpetra** [LLNL/hiop#473]
```
/ccs/home/cpetra/work/projects/hiop/src/LinAlg/hiopLinSolverSparseCUSOLVER.hpp:64:10: fatal error: klu.h: No such file or directory
   64 | #include "klu.h"
```

**Comment by cnpetra** [comment]
@kswirydo @pelesh

**Comment by pelesh** [comment]
Class `hiopLinSolverSparseCUSOLVER` implements LU factorization with cuSOLVER LU _refactorization_ functions. It requires KLU to perform symbolic factorization. This class should not be built when KLU is not available, so HiOp should build with or without KLU.

How did you build HiOp to get to that error? CMake should have prevented that. Could you provide your CMake build options?

**Comment by cnpetra** [comment]
isn't KLU turned on when `HIOP_USE_CUSOLVER` is on, [here](https://github.com/LLNL/hiop/blob/658205f4c15893ed42055b2b286b513f090359f2/CMakeLists.txt#L250)?

When `HIOP_USE_CUSOLVER` is on, `hiopLinSolverSparseCUSOLVER` is compiled, but the include of and calls to KLU are not guarded.

**Comment by pelesh** [comment]
> When `HIOP_USE_CUSOLVER` is on, `hiopLinSolverSparseCUSOLVER` is compiled, but the include of and calls to KLU are not guarded.

No, the issue is that `hiopLinSolverSparseCUSOLVER` should not be built when KLU is not found. The fix should be to:
1. Rename `HIOP_USE_CUSOLVER` to `HIOP_USE_CUSOLVER_LU` to avoid confusion with ambiguous name
2. If KLU is not found set  `HIOP_USE_CUSOLVER_LU` to `Off` and print warning.

**Comment by pelesh** [comment]
> When `HIOP_USE_CUSOLVER` is on, `hiopLinSolverSparseCUSOLVER` is compiled, but the include of and calls to KLU are not guarded.

No, the issue is that `hiopLinSolverSparseCUSOLVER` should not be built when KLU is not found. The fix should be to:
1. Rename `HIOP_USE_CUSOLVER` to `HIOP_USE_CUSOLVER_LU` to avoid confusion with ambiguous name
2. If KLU is not found set  `HIOP_USE_CUSOLVER_LU` to `Off` and print warning.

**Comment by cnpetra** [comment]
OK, so the CMakefile TODO left [here](https://github.com/LLNL/hiop/blob/658205f4c15893ed42055b2b286b513f090359f2/CMakeLists.txt#L249) does not apply anymore?
