### ISSUE TITLE
How to select vector pattern

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#53]
It might be helpful to specify and better document how to select vector pattern. Currently pattern is selected by a vector of `1.0`s and `0.0`s in double precision. Rules are a little vague as to what happens in case that pattern vector element is neither one nor zero. Possible solutions I see are:
1. Strictly enforce pattern vectors have elements zero (not selected) and one (selected) only. 
    - Pros: No changes to existing vector kernel implementations, provides more flexibility for future GPU implementation of vector kernels.
    - Cons: Potentially bug prone, need to add assertions (at least in debug mode) enforcing pattern vector values to be either one or zero.
2. [SUNDIALS](https://github.com/LLNL/sundials) way: zero means not selected, > zero means selected.
    - Pros: Safer than 1., no changes to existing vector kernel implementations needed.
    - Cons: Provides less flexibility for GPU implementations, undefined when value < 1.
3.   Define pattern vector as a vector of booleans.
    - Pros: Safe implementation
    - Cons: Less flexibility for GPU implementations, more invasive changes to the code needed.

The argument related to GPU implementations is something like this: If pattern vector elements are either one or zero, then instead of using conditionals, which could cause warp divergence, one could simply do elementwise multiply with pattern vector to select the pattern. For memory bound computations, this could lead to a better performing implementation, I think.  

@cnpetra @ashermancinelli

**Comment by cnpetra** [comment]
pattern vectors should have only 0. (not selected) and 1. elements (selected). Any other values mean there is a bug. There should be plenty of asserts to detect non 1 or 0 value. As you mentioned , this is chosen specifically with accelerators in mind.  What I am saying that 1. is already in there or at least should be.

**Comment by pelesh** [comment]
Will use option 1. for all future contributions. Thanks for clarifying.
