### ISSUE TITLE
API for hiopMatrixSparseTriplet has implementation specific arguments

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#54]
Some of the methods of `hiopMatrixSparseTriplet` class have an argument, which is a reference to a specific matrix implementation (see e.g. [`transAddToSymDenseMatrixUpperTriangle`](https://github.com/LLNL/hiop/blob/master/src/LinAlg/hiopMatrixSparseTriplet.hpp#L66) method). This could potentially lead to cumbersome solutions when porting this class to hardware accelerators (e.g. GPU).

A minimally invasive way to go about this would be to add an `enum` to matrix base class with matrix type IDs, as well as a virtual method to return the matrix type ID. Similar was done in [SUNDIALS](https://github.com/LLNL/sundials/blob/master/include/sundials/sundials_matrix.h#L59). 

With such modification, method `transAddToSymDenseMatrixUpperTriangle` can take reference to virtual `hiopMatrix` class as the input argument, and then check in the implementation if a compatible matrix type was passed. The implementation of `transAddToSymDenseMatrixUpperTriangle` can then select computation specific to the matrix layout or throw an exception if matrix type is incompatible. 

This could keep API cleaner and provide more extensibility. The downside of this approach is that passing an incompatible matrix type would be caught at runtime instead of at compile time. A more comprehensive solution would be to use template parameters to specify matrix layout, but that would require more significant changes to the code.

@cnpetra @ashermancinelli

**Comment by cnpetra** [comment]
that is intended design, at least with the mentioned method(s) and for the time being until it becomes apparent how the porting looks like.

**Comment by pelesh** [comment]
CC: @CameronRutherford @JuanDiegoMontoya

**Comment by cnpetra** [comment]
I see a potential need to include such methods in an  interface (for the sparse matrices) when porting, but it really depends on the specific of the device implementation, for example this would/should not be needed (ideally) if the hardware abstraction layer can run cpu or gpu in a way that is oblivious to the code using this class... like in RAJA vector class.

**Comment by ashermancinelli** [comment]
> I see a potential need to include such methods in an interface...

This would make testing and transitioning to new implementations much easier as you mentioned. Ideally every internal method deals with only an interface so we can swap out implementations as needed.

**Comment by pelesh** [comment]
I should have clarified that using matrix type IDs is a transitional solution that will help us experiment with GPU implementations with minimal changes to the existing HiOp code until we understand better how to refactor the API to support hardware accelerator code in a long term. By using matrix/vector type IDs and dynamic casts we can enforce the same matrix compatibility requirements without major refactoring of the API and leaving existing CPU code largely intact.

**Comment by ashermancinelli** [comment]
> a transitional solution...

I only worry that any transitional solution will create too much inertia and we'll never actually solve the design challenge. Other than that, this seems fine to me!

**Comment by pelesh** [comment]
Per our discussion, refactoring interfaces would be a much better long-term solution, and per @ashermancinelli's assessment, it wouldn't take too much effort. We could think of inheritance structure like this:
* `hiopMatrix` - pure virtual base matrix class
    * `hiopMatrixDense` - virtual, base class for all dense matrix implementations
        * `hiopMatrixDenseRowMajor` - current implementation of `hiopMatrixDense` renamed
        * `hiopMatrixDenseRowMajorRaja` - portable dense matrix implementation using RAJA
    * `hiopMatrixSparse` - virtual base class for all sparse matrix implementations
        * `hiopMatrixSparseTriplet` triplet implementation of the sparse matrix
        * `hiopMatrixSparseTripletRaja` - portable triplet implementation using RAJA
        * `hiopMatrixSparseCSR` - if ever needed ...

**Comment by ashermancinelli** [comment]
I am a big fan of the naming & inheritance scheme you've laid out. I was in the process of writing up something just like it 😄 

In my opinion, we should make this the highest priority so we can build on top of this internally with our additional unit/integration tests. I will make an internal MR and expedite this work unless @cnpetra disagrees.

**Comment by cnpetra** [comment]
looking quite good, will take the final look when the PR comes in here.
