### ISSUE TITLE
Unable to build with CUDA and without RAJA

### ISSUE THREAD

**Issue by CameronRutherford** [LLNL/hiop#547]
https://github.com/LLNL/hiop/blob/develop/CMakeLists.txt#L273

**Comment by CameronRutherford** [comment]
cc @fritzgoebel

**Comment by cnpetra** [comment]
I recently introduced that. I am very much for not having RAJA as dependency for anything cuSparse, but for now we need RAJA vectors in the condensed and normal equations linear systems. 

A quick fix would be to not build condensed and normal equations code when RAJA is not present. All the other HIOP_SPARSE =ON code should work without RAJA. 

Essentially guard
https://github.com/LLNL/hiop/blob/eaf241757999837bd62a3daf4597a52a6a2b7814/src/Optimization/CMakeLists.txt#L20
and 
https://github.com/LLNL/hiop/blob/eaf241757999837bd62a3daf4597a52a6a2b7814/src/Optimization/CMakeLists.txt#L21
with `if(HIOP_USE_RAJA)`

I expect code in the examples also need to be guarded in one or two places.

**Comment by CameronRutherford** [comment]
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/hiop/package.py

Currently it is valid to build `hiop+ginkgo+cuda` or `hiop+ginkgo+rocm` in the spack package. I think this is what @fritzgoebel was building recently, and so we might want to tweak that CMake logic if that configuration is possible.

Currently `hiop+cuda+cusolver` is also valid, but it seems that we would be missing raja in that case.

**Comment by cnpetra** [comment]
closed by PR#549
