### ISSUE TITLE
Submodule not downloaded

### ISSUE THREAD

**Issue by SanPen** [LLNL/hiop#556]
Hi, 

I just downloaded the 0.7.0 release on ubuntu 20.04 and after installing missing dependencies (would be cool to list all those for *nix systems) I get this:

```
CMake Error at cmake/HiOpCheckGitSubmodules.cmake:22 (message):
  It seems required submodule was not downloaded! Please update submodules
  manually with the following command and try again.

  	$ git submodule update --init --recursive

Call Stack (most recent call first):
  CMakeLists.txt:202 (include)
```

I could indeed clone the repo and follow the instructions, but what would be the point on having a release?
Hence, please, publish a complete release.

Best regards,
Santiago

**Comment by cnpetra** [comment]
thank you for reporting, we'll look into it

**Comment by pelesh** [comment]
Santiago, could you please share full output of your cmake execution? Also, what happens when you try to update git submodules manually as the error message suggests?

**Comment by CameronRutherford** [comment]
This is intended behaviour, but I can see how this is unclear.

CMake error is suggesting that you need to initialise submodule manually per @pelesh's suggestion.

cmake/HiOpCheckGitSubmodules.cmake - our CMake config should run this for you automatically, so I'm surprised you are running into this error. Perhaps `find_package(Git)` is failing, and hence your CMake isn't cloning things.

With respect to maintaining a list of required dependencies for *nix systems, we maintain a spack package for HiOp https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/hiop/package.py

Two notes from this
- We should update our GitHub docs to reflect submodule support
- We should update our Spack package with 0.7.0
- We should update ExaGO/HiOp docs to include something like `installing_with_spack`

I'm in the middle of refactoring the ExaGO spack configuration to use a submodule, and so this should be much easier when that's working and fully documented.

**Comment by cnpetra** [comment]
the same error also reported here: https://github.com/xsdk-project/xsdk-issues/issues/187#event-7594423222

I think it makes sense to not error out when the check for `git submodule` fails. Just give a warning that the eigen needs to be installed manually given that `git submodule` is not available.

**Comment by cnpetra** [comment]
Santiago (@SanPen), could you please take look at the new release (https://github.com/LLNL/hiop/releases/tag/v0.7.1) and let us know if it works for you. It should address all the issues you reported.
