### ISSUE TITLE
Check the implementation in hiopLinAlgebraFactory

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#577]
Some useless return functions after assertions.
For example, the following return function will never been called
```
     assert(false && "requested memory space not available because Hiop was not"
                      "built with CUDA support");
      return new hiopVectorPar(glob_n, col_part, comm)
```

**Comment by cnpetra** [comment]
`return` statement gets executed under ndebug builds, but I see how that can be confusing and inconsistent.

**Comment by nychiang** [comment]
> `return` statement gets executed under ndebug builds, but I see how that can be confusing and inconsistent.
See Cameron and Slaven's discussion in PR #572
