### ISSUE TITLE
User can't set verbosity level without re-compiling HIOP

### ISSUE THREAD

**Issue by junkudo** [LLNL/hiop#6]
Hey,
Just ran into this one.

In `hiopNlpFormulation.cpp`, you create a hiop logger with the verbosity level as a parameter.  However, you are immediately grabbing the verbosity level option from the default constructed `hiopOptions` which prohibits anyone from actually specifying the verbosity level :

```c++
  options = new hiopOptions(/*filename=NULL*/);

  hiopOutVerbosity hov = (hiopOutVerbosity) options->GetInteger("verbosity_level");
  log = new hiopLogger(this, hov, stdout);
```

**Comment by cnpetra** [comment]
fixed with commit 608740514975e0cbf131a26e8d40e94b1c292316 (master)
