### ISSUE TITLE
Spack CI failures

### ISSUE THREAD

**Issue by cnpetra** [LLNL/hiop#601]
One of the Spack-based CIs started to fail recently. Namely, `hiop@develop~mpi+raja~shared~kron~sparse`

This happens for all the PRs/branches. It reports 
```
/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/cmake-3.23.3-
          u7spcudumu4d6olw2rjdhugl6g6z6ndq/bin/cmake: error while loading share
          d libraries: libxml2.so.2: cannot open shared object file: No such fi
          le or directory
```

**Comment by CameronRutherford** [comment]
My guess is that `ubuntu-latest` (the image that we do spack builds with) recently removed `libxml2` as a part of that container runtime for whatever reason, and so now this error is showing up.

I will experiment with a few things, but I am unsure why this is suddenly an issue. Perhaps pinning a container version would be best in the future to avoid these "surprise" updates in the future.

**Comment by cnpetra** [comment]
@CameronRutherford that explains it
