### ISSUE TITLE
Possible bug in hiopMatrixDenseRowMajor::timesMatTrans

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#61]
It seems there may be a bug in the MPI part of the `hiopMatrixDenseRowMajor::timesMatTrans` function. Perhaps [this line](https://github.com/LLNL/hiop/blob/6f7e993ad942e06dae9dc48c00343af612ce4c3d/src/LinAlg/hiopMatrixDenseRowMajor.cpp#L639) should instead be:
```c++
  double* Wglob= W.new_mxnlocal_buff(); //[n2Red];
```
Local buffers of `this` and `W` matrix are not necessarily the same.

CC @JuanDiegoMontoya

**Comment by cnpetra** [comment]
I am afraid there is. Your suggestion should fix it. 

It went undetected for years because in the quasi-Newton code that uses this, `this->n` is larger than `W.n()`
