### ISSUE TITLE
Bug in LinAlg/hiopMatrixSparseCsrCuda.cpp

### ISSUE THREAD

**Issue by pate7** [LLNL/hiop#611]
Howdy All! 

I believe I have found a syntax error in `src/LinAlg/hiopMatrixSparseCsrCuda.cpp`. On line 157, there is the statement 

```cpp
  st == cusparseSpGEMM_destroyDescr(gemm_sp_descr_);
```
where `st` is a `cuparseStatus` object. It appears that the intended behavior here is to assign `st` to the 
result of `cusparseSpGEMM_destroyDescr`, but the double equal sign is performing a comparison instead of assignment.

**Comment by cnpetra** [comment]
Indeed, it's a typo

**Comment by pate7** [comment]
Cool. So what's next? Should I put in a PR fixing it? Do y'all put in a PR fixing it? Some third option where we don't fix it?

**Comment by cnpetra** [comment]
PR the fix please. I can get to it later today as well. Third option is not an option :)

**Comment by pate7** [comment]
Can do!

**Comment by pate7** [comment]
Do I need any sort of repo permissions? I tried to push my branch up and it got rejected.

**Comment by cnpetra** [comment]
closed by PR#612
