### ISSUE TITLE
hiopVectorCuda.hpp should not include hiop_cusolver_defs.hpp

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#629]
HiOp CUDA vector header file `hiopVectorCuda.hpp` includes `hiop_cusolver_defs.hpp`, which contains definitions of experimental and unsupported GLU solver. These definitions are needed only for cuSOLVER LU interface. It is probably better idea to just:
```c++
#include <cublas_v2.h>
```

**Comment by pelesh** [comment]
CC @nychiang

**Comment by nychiang** [comment]
Good to know! Thanks! @pelesh
