### ISSUE TITLE
hiopMatrixMDS copyFrom method will always fail

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#63]
In `hiopMatrixMDS::copyFrom`, we have:
```cpp
  virtual void copyFrom(const hiopMatrixMDS& m)
  {
    mSp->copyFrom(*m.mSp);
    mDe->copyFrom(*m.mDe);
  }
```
Yet, `hiopMatrixSparseTriplet::copyFrom` has:
```cpp
void hiopMatrixSparseTriplet::copyFrom(const hiopMatrixSparseTriplet& dm)
{
  assert(false && "this is to be implemented - method def too vague for now");
}
```
Therefore this method will always fail. Should it not be a method of `hiopMatrixMDS` or should there be an implementation for `hiopMatrixSparseTriplet::copyFrom` that will not immediately assert?

**Comment by cnpetra** [comment]
`hiopMatrixSparseTriplet::copyFrom` requires some extra care/work to be implemented efficiently, and since it is not needed, I just didn't implement it.

**Comment by ashermancinelli** [comment]
In your opinion, should we 1) keep the methods as they are and simply document future intent in the header, 2) same as (1) but track discussion on this in an issue, 3) remove some of the non-functional kernels, or 4) leave as is?

I think if we go with (1) or (3), adding these changes to #66 would be the best use of our time.

**Comment by cnpetra** [comment]
I find 1) a balanced approach...

**Comment by cnpetra** [comment]
addressed, but please feel free to reopen if not the case
