### ISSUE TITLE
hiopMatrixSparse interface decisions

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#64]
In our internal branch, the linear algebra factory has a method (`createMatrixSparse`) to create an instance of the abstract class `hiopMatrixSparse`, choosing the appropriate implementation (e.g. RAJA vs default).

Seeing that there are other implementations of sparse matrices, ***how should we alter the factory class API to create other kinds of sparse matrices?***

A few options:
- Pass options as template parameters (storage type of csr/coo, complex/real-only, sym/non-sym, etc)
- Pass options as parameters of enum types
- Pass options as parameters of string types
- Create different factory methods for different types of sparse matrices
    - i.e. methods like `createMatrixSparseSym`, `createMatrixSparse`, and others

CC @pelesh

**Comment by cnpetra** [comment]
I think this has been discussed and addressed, please confirm.

**Comment by ashermancinelli** [comment]
I can confirm.
