### ISSUE TITLE
RAJA must be used when CUDA is selected.

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#675]
spack formula `hiop@develop+cuda`  failed due to [this section](https://github.com/LLNL/hiop/blob/2378fde5cc371047227c396ddaaf58b6453f928c/src/LinAlg/LinAlgFactory.cpp#L357-L373) requires RAJA (but it is within the section without using RAJA).

@cameronrutherford While I will work on updating the CMake file in hiop, we also need to update the spack formula, to activate RAJA when cuda is selected.

**Comment by cameronrutherford** [comment]
See https://github.com/spack/spack/pull/42407 - one line change to add this logic :)

**Comment by cameronrutherford** [comment]
@nychiang consider adding a warning to CMake for those users that are configuring HiOp without Spack
