### ISSUE TITLE
Are versions retagged?

### ISSUE THREAD

**Issue by haampie** [LLNL/hiop#677]
While checking whether commit hashes / tags are still in sync in the Spack package manager I noticed:

```diff
-    version("0.4.4", tag="v0.4.4", commit="e858eefa6b914f5c87c3717bbce811931ea69386")
+    version("0.4.4", tag="v0.4.4", commit="4e3faa9963e83cd7f2a388bfcc1e402dc86fc81d")
...
-    version("0.4.1", tag="v0.4.1", commit="3f269560f76d5a89bcbd1d3c4f9f0e5acaa6fd64")
+    version("0.4.1", tag="v0.4.1", commit="281adb5fb335642446e0804a2669b97d8ef62998")
```

Somehow the 0.4.1 commit https://github.com/LLNL/hiop/commit/281adb5fb335642446e0804a2669b97d8ef62998 says

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

is that a bug in GitHub or did something weird happen when re-tagging?

**Comment by cnpetra** [comment]
I am unsure what could have happened that orphaned the commit you're referring to. We'll investigate on our end.

**Comment by nychiang** [comment]
@cameronrutherford FYI

**Comment by cameronrutherford** [comment]
Honestly no idea? I figure the easiest fix is to find the correct commit in this GitHub and change what commit that tag points to, then PR into spack.

Maybe this would explain some weird failures we were seeing in xSDK work...

**Comment by cameronrutherford** [comment]
The commit history is certainly a little messier than I would like. For some weird reason the tagged 0.4.1 commit is in a place right before 0.5.0... No idea what is going on with the 0.4.4 version if that was also somehow changed...

I am closing this issue as I don't really know what happened? Maybe someone else has an idea but I am rather lost as to what might have caused a recent change like this. Maybe someone force pushed at some point?
