### ISSUE TITLE
Cannot build with CUDA flag set ON

### ISSUE THREAD

**Issue by finkeljos** [LLNL/hiop#678]
Hi,

I am trying to build hiOp on an Nvidia GPU node on my local cluster.

After a fresh clone on the develop branch, I enter an empty build dir enter the command

cmake -DHIOP_USE_GPU=ON -DHIOP_USE_CUDA=ON -DCMAKE_BUILD_TYPE=Release ..

But when building the compiler complains that 

[Picture1.pdf](https://github.com/LLNL/hiop/files/14069426/Picture1.pdf)

I don't understand why the .cpp code has any mention of RAJA if I am not explicitly enabling it. Is there a missing ifdef in this file? It is my understanding I should be able to build only with cuda in order to access cuBLAS, cuSolver etc.

I am using gcc, cuda and OpenMPI modules, all of which are found by Cmake, including my custom build of MAGMA.

**Comment by cnpetra** [comment]
raja is currently a dependence for cuda.

**Comment by cnpetra** [comment]
see also https://github.com/LLNL/hiop/pull/676

**Comment by cnpetra** [comment]
closing this since a partial fix has been done in PR #676. We will remove RAJA as a dependency in the not-so-far future.
