### ISSUE TITLE
Review RAJA kernels

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#72]
Review RAJA kernels (currently in `raja-dev` branch) and flag potential bottlenecks. The purpose of this review is pre-screening of potential performance issues to give us heads up what to pay attention to when profiling the performance.

The current implementation of RAJA kernels was done with objective to ensure accurate computations. Some kernels, such as `hiopVectorRajaPar::projectIntoBounds`, are implemented in a way that is not quite "GPU friendly". Help from RAJA developers in identifying other potential bottlenecks and suggestions how to implement these kernels better is very much appreciated.

RAJA kernels are implemented in following HiOp classes:
- `hiopVectorRajaPar`
- `hiopMatrixRajaDense`
- `hiopMatrixRajaSparseTriplet`
- `hiopMatrixRajaSymSparseTriplet`

Currently, RAJA kernels run only within unit tests. See tests in:
- `testVector.cpp`
- `testMatrix.cpp`
- `testMatrixSparse.cpp`

CC @davidbeckingsale @rhornung67

**Comment by pelesh** [comment]
Example 4 in HiOp was adapted to run with RAJA/Umpire libraries. HiOp now runs with RAJA-based linear algebra kernels on GPU when using unified virtual memory. There are still a few places where HiOp reaches directly to linear algebra data directly on the host. Examples include matrix inertia calculation and removing fixed variables.

**Comment by cnpetra** [comment]
is inertia calculation described by issue #79 ?

**Comment by pelesh** [comment]
> is inertia calculation described by issue #79 ?

Yes, you are correct. There are a few other places where the optimization algorithm reaches to data directly and assumes it is on the host. Removing fixed variables is another example, but there seem to be more. We still need to identify and document all of such instances.
