### ISSUE TITLE
Insufficient Documentation for hiopMatrixSymSparseTriplet::transAddToSymDenseMatrixUpperTriangle

### ISSUE THREAD

**Issue by CameronRutherford** [LLNL/hiop#78]
For the fuction [`transAddToSymDenseMatrixUpperTriangle`](https://github.com/LLNL/hiop/blob/7d701c5dc9f6b70dd4819e247589e35f969ebd94/src/LinAlg/hiopMatrixSparseTriplet.cpp#L561), it is unclear given the current documentation which matrix should be transposed. From what is in the kernel, it appears as though it is the symmetric sparse triplet matrix that is transposed. If this is the case, then this may be related to issue #77.

If it is the output matrix that should be transposed, then the kernel should be modified, and documentation should be updated accordingly.

**Comment by cnpetra** [comment]
when `trans` is before the verb/operation (e.g., "Add"), it applies to `this` (most of of these cases, `trans` prefixes the method name)
```
this->transAddToXXX(M)
``` 
When the method's argument involves some transpose operation, `trans` would be after the verb
```
this->addToXXXTrans(M);
```

**Comment by CameronRutherford** [comment]
Thank you for the clarification. Since this is consistent across the codebase, I am going to close this issue.
