### ISSUE TITLE
Counting negatives in Hxs should be implemented as a vector kernel?

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#79]
Consider implementing loop that is counting negative eigenvalues in [`hiopKKTLinCompressedMDSXYcYd` class](https://github.com/LLNL/hiop/blob/master/src/Optimization/hiopKKTLinSysMDS.cpp#L274) as a vector kernel and adding it to the abstract vector interface. Otherwise, method `hiopKKTLinSysCompressedMDSXYcYd::update` depends on implementation detail of the `Hxs_` vector.

This loop will not run on GPU, for example.

**Comment by cnpetra** [comment]
indeed, thanks for reporting this

**Comment by cnpetra** [comment]
addressed by eca78f9f8db9c9cbefa6b1a4b44568b6a10f1f39
