### ISSUE TITLE
GPU compute mode option

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#80]
It would be good to add "gpu" as a "compute_mode" option in HiOp. However, this option is not independent of "mem_space" selection. Here is the summary of compute mode and memory space option compatibilities:
1. "cpu" option works only with "default", "host" and likely "um" memory space options.
2. "hybrid" works with all but "device" memory space option.
3. "gpu", if added, would work with "um", "pinned" or "device" options.

We can simply document this and expect user to select a meaningful combination or we can add some logic to HiOp options class that would warn user or when incompatible combination was selected and fall back to the next best thing.

If HiOp is built without RAJA support, only "default" memory space is available.

Options "um", "pinned" or "device" are available only if HiOp is built with GPU support (for now it's CUDA only) turned on.

CC @ashermancinelli @cnpetra

**Comment by cnpetra** [comment]
>  warn user or when incompatible combination was selected and fall back to the next best thing

this can/should be done in 
https://github.com/LLNL/hiop/blob/2252b90bc40f86b8d842da6fec30105feddbf647/src/Utils/hiopOptions.cpp#L292
