### ISSUE TITLE
Cmake fails to find the installed lapack on Lassen

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#83]
Cmake cannot find the installed Lapack on Lassen.
In configuration, it shows: 
    Found LAPACK libraries: /usr/lib64/libessl.so;/usr/lib64/libblas.so;
However, it gives error message with compiling the code:
    hiopKKTLinSys.cpp:(.text+0x7c24): undefined reference to `dposvx_'

Same error happens when different version of Lapack is loaded by command "module".

**Comment by pelesh** [comment]
@nychiang, could you please provide output from when you run `make VERBOSE=1`? Also, what branch are you using?

**Comment by nychiang** [comment]
I started from the master branch.
Here I attached two log files, from commands CMake and make.
[log1.txt](https://github.com/LLNL/hiop/files/5278258/log1.txt)
[log2.txt](https://github.com/LLNL/hiop/files/5278259/log2.txt)

**Comment by pelesh** [comment]
Have you tried building with newer version of GCC? You are building with 4.9.3 which is pretty old. I haven't tested HiOp with that.

**Comment by nychiang** [comment]
Yes, I had tried building with GCC 8.3.1 with different version of Lapack, but they all gave me the same error.
Cosmin mentioned to me he also noticed this issue, i.e., some versions of cmake cannot find correct Lapack library.
I tried two versions of cmake and both gave me the same error.
We decide to hard code the path to Lapack, and move on to implement the sparse linear algebra first.

NY

**Comment by pelesh** [comment]
@nychiang if I look at your Cmake configuration
```shell
-- Found LAPACK libraries: /usr/lib64/libessl.so;/usr/lib64/libblas.so;-lpthread;-lm;-ldl
```
and the linking line in your build log that fails
```shell
/usr/tcetmp/bin/c++ -L/usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-2020.08.19/lib -pthread CMakeFiles/nlpDenseCons_ex1.exe.dir/nlpDenseCons_ex1.cpp.o CMakeFiles/nlpDenseCons_ex1.exe.dir/nlpDenseCons_ex1_driver.cpp.o -o nlpDenseCons_ex1.exe  -Wl,-rpath,/usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/lib ../../libhiop.a /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/lib/libmpiprofilesupport.so /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/lib/libmpi_ibm.so /usr/tce/packages/gcc/gcc-4.9.3/gnu/lib64/libgomp.so -lpthread /usr/lib64/libessl.so /usr/lib64/libblas.so -lpthread -lm -ldl /usr/lib64/libessl.so /usr/lib64/libblas.so -lpthread -lm -ldl /g/g92/chiang7/software/HSL/MA57/lib/libma57.a /g/g92/chiang7/software/METIS_4/lib/libmetis.a -lgfortran 
../../libhiop.a(hiopKKTLinSys.cpp.o): In function `hiop::hiopKKTLinSysLowRank::solveWithRefin(hiop::hiopMatrixDense&, hiop::hiopVector&)':
hiopKKTLinSys.cpp:(.text+0x726c): undefined reference to `dposvx_'
../../libhiop.a(hiopKKTLinSys.cpp.o): In function `hiop::hiopKKTLinSysLowRank::solve(hiop::hiopMatrixDense&, hiop::hiopVector&)':
hiopKKTLinSys.cpp:(.text+0x7c24): undefined reference to `dposvx_'
collect2: error: ld returned 1 exit status
```
I find that Lapack libraries CMake found seem to be correctly linked. 

I am curious what linker flags did you hard wire to make this work?

CC @ashermancinelli

**Comment by nychiang** [comment]
To make it work, I just add the path to lapack into CMakeList.txt:
set(LAPACK_LIBRARIES "-lgfortran;/usr/lib64/liblapack.so;-lpthread;-lm;-ldl")

**Comment by pelesh** [comment]
It seems to me that the problem was in the ESSL module, which is the Lapack implementation you chose. You are hard-wiring to the Lapack version that was shipped with the OS on your machine. Try unloading any Lapack module, commenting out the line
```cmake 
set(LAPACK_LIBRARIES "-lgfortran;/usr/lib64/liblapack.so;-lpthread;-lm;-ldl")
```
and re-running CMake. That should give you the same linking options as those you specified manually.

**Comment by nychiang** [comment]
No, it doesn't work. If I don't hard-wiring to liblapack.so, the CMake command\
 find_package(LAPACK REQUIRED)\
will find ESSL as the default lapack module. 
See the log files from a clean installation and the modules I used, i.e., the latest version of CMake and GCC on Lassen. 
[log2.txt](https://github.com/LLNL/hiop/files/5294005/log2.txt)
[log1.txt](https://github.com/LLNL/hiop/files/5294006/log1.txt)
![Capture](https://user-images.githubusercontent.com/10119740/94465912-7a531a00-0175-11eb-8df6-0217b1720d09.JPG)

**Comment by pelesh** [comment]
In that case, we just need to cache `LAPACK_LIBRARIES` variable, so that user can change it in case the system configuration leads CMake to an undesired library. I would think CMake can do very little if ESSL is on your system library path before the Lapack library you actually want to use. 

You could also configure your build with `-DLAPACK_LIBRARIES="-lgfortran;/usr/lib64/liblapack.so;-lpthread;-lm;-ldl"`; I think that should work, as well.

**Comment by nychiang** [comment]
Sure. It should work if I pass the path as an additional environment variable to cmake.
I did this trick for another package.
Okay, I will remove the hard-coded path to lapack/metis4/ma57 in CMakelist, and externally apply them.

Thanks!

**Comment by cnpetra** [comment]
apparently, `dposvx` is not present in libessl.so, at least not on lassen.llnl.gov. This is the root cause of the problem. It will compile with  liblapack, but we may want to use libessl for (possible) better performance. The good news is that the GPU-based code does not need  `dposvx`, so we have the option to use libessl (requires changes to the build system).

**Comment by cnpetra** [comment]
a temporary fix is as suggested by @pelesh: use cmake with `-DLAPACK_LIBRARIES="-lgfortran;/usr/lib64/libblas.so;/usr/lib64/liblapack.so;-lpthread;-lm;-ldl"` (make sure you include blas lib, otherwise won't compile)

and use the fix for the cmake build system from ef195e0

**Comment by nychiang** [comment]
Another solution:  link the noconflict routines before LAPACK, i.e., 
-lesslnoconflict -llapack

This will use the optimized versions of the LAPACK routines that are in ESSL, and use liblapack.a for the ones which are not in ESSL.

**Comment by cnpetra** [comment]
interesting, that would be ideal, indeed.

can that be used with cmake with `-DLAPACK_LIBRARIES="....."` or CMakeLists.txt needs to be edited?

**Comment by ashermancinelli** [comment]
Defining with cmake as you've suggested would work, though it would override any discovery of lapack libraries cmake might otherwise do. If you're sure you can find all the libraries needed that would be a good solution 😄

**Comment by pelesh** [comment]
> Defining with cmake as you've suggested would work, though it would override any discovery of lapack libraries cmake might otherwise do. If you're sure you can find all the libraries needed that would be a good solution 😄

@ashermancinelli it might be a good idea to cache `LAPACK_LIBRARIES` so that user can fix it if user's input was incorrect or wrong library was found.

**Comment by cnpetra** [comment]
> Defining with cmake as you've suggested would work, though it would override any discovery of lapack libraries cmake might otherwise do. If you're sure you can find all the libraries needed that would be a good solution 😄

this manual override is a last resort

**Comment by cnpetra** [comment]
> Another solution: link the noconflict routines before LAPACK, i.e.,
> -lesslnoconflict -llapack
> 
> This will use the optimized versions of the LAPACK routines that are in ESSL, and use liblapack.a for the ones which are not in ESSL.

but you need to unpack libessl manually, right? or is `-lesslnoconflict` available on lassen?

**Comment by nychiang** [comment]
I tested it. It is NOT available on lassen, but this is the command given by LC.
However, I use the command -lessl -llapack (inspired by the strumpack user manual), and it works fine.
Passed all the tests, i.e., EX1 - EX5.
