### ISSUE TITLE
Developer Readme Tests

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#89]
In `README_developers.md` the required tests involve using clang tools for address sanitization. Clang does not work so readily with openmp which is now a dependency for the new RAJA linear algebra library. To run these we have to disable `HIOP_USE_RAJA`. @cnpetra would you still like to have clang tools checks for the non-raja parts of hiop or should we pursue other tests as prerequisites for submitting PRs?

**Comment by cnpetra** [comment]
up to you

**Comment by ashermancinelli** [comment]
I'll submit PR for readme. We have a more thorough build matrix planned for down the line so we'll save tooling for RAJA builds for later.

**Comment by ashermancinelli** [comment]
Finishing in our internal repo.
