### ISSUE TITLE
Sparse algebra interface and lambda .= 0 at first iteration

### ISSUE THREAD

**Issue by michel2323** [LLNL/hiop#95]
Finally, I have good description of this case. The MOI interface is working fine using the dense algebra. With the sparse one, I have the following issue.

I pass this sparsity pattern to Hiop:

`iHSS = Int32[0, 1, 2, 6, 9, 15, 18, 7, ..., 14, 16, 21, 22, 23, 9, 13, 14, 18, 22, 23]`
`jHSS = Int32[0, 1, 2, 6, 6, 6, 6,..., 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23`

The relevant entries are only the first 3.

At the first iteration on the IEEE 9 bus case with 3 generators and the lambdas being initialized to 0 I get the following Hessian:

`nzval = [2200.0, 1700.0, 2450.0, 0.0, ..., -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0]`

Because the multipliers lambda are 0 this seems right to me, given there are 3 generators.

Hiop then aborts with this message:

```
iter    objective     inf_pr     inf_du   lg(mu)  alpha_du   alpha_pr linesrch
   0  8.3631250e+03 1.550e+00  3.530e+03  -1.00  0.000e+00  0.000e+00  -(-)
[Warning] hiopLinSolverIndefDense error: 11 entry in the factorization's diagonal
is exactly zero. Division by zero will occur if it a solve is attempted.
[Warning] hiopLinSolverIndefDense error: 11 entry in the factorization's diagonal
is exactly zero. Division by zero will occur if it a solve is attempted.
julia: /scratch/mschanen/git/hiop/src/Optimization/hiopPDPerturbation.hpp:184: bool hiop::hiopPDPerturbation::compute_perturb_singularity(double&, double&, double&, double&): Assertion `delta_cc == 0. && delta_cd == 0.' failed.
```

If I set the multipliers to nonzero at the first iteration, it works fine, and the problem even converges to the right solution. So I'm wondering what is going on? Is this expected behavior?

Thanks!

**Comment by cnpetra** [comment]
Works like it's supposed to, but will change the starting procedure to call the Hessian a bit later in the initialization process, which will make lambdas nonzero in most of the cases.

**Comment by cnpetra** [comment]
I pushed the fix #c7cbacc

**Comment by cnpetra** [comment]
let me know is `starting_point` solution works and will close the issue as the LSQ initialization will be handled in issue #97

**Comment by cnpetra** [comment]
closing this as issue #97 covers the require developments to fix this issue.
