### ISSUE TITLE
`addToSymDenseMatrixUpperTriangle` and `transAddToSymDenseMatrixUpperTriangle` for sparse matrix have never been used

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#98]
functions `addToSymDenseMatrixUpperTriangle` and `transAddToSymDenseMatrixUpperTriangle` for sparse matrix have never been used.
The optimization routines under 'hiopKKTLinMDS' only need to use this function for its dense part [(see here) ](https://github.com/LLNL/hiop/blob/2252b90bc40f86b8d842da6fec30105feddbf647/src/Optimization/hiopKKTLinSysMDS.cpp#L166 ), and we always assume the sparse part of HessMDS is a diagonal matrix (in order to perform its inverse function efficiently).

New functions `addToSym**Sparse**MatrixUpperTriangle` may be required for the sparse linear implementation, which is handled in #85. The RAJA variants may be implemented later.

**Comment by cnpetra** [comment]
@pelesh @ashermancinelli 
I removed `addToSymDenseMatrixUpperTriangle` completely from hiop

`transAddToSymDenseMatrixUpperTriangle` is (needed but) only for GENERAL matrices. 

`addUpperTriangleToSymDenseMatrixUpperTriangle` is only for SYMMETRIC matrices. 

I've updated the documentation for the methods in the base class.

**Comment by cnpetra** [comment]
@nychiang yes, the two methods should be specialized to update sparse matrices as you said
